# Generated by Django 5.2.7 on 2026-05-30 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0004_termo_fecha_ultimo_servicio_and_more'),
        ('ordenes_compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='es_insumo',
            field=models.BooleanField(default=False, verbose_name='¿Es insumo general (sin unidad)?'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='termo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='flota.termo', verbose_name='Thermo'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='tipo_mantenimiento',
            field=models.CharField(blank=True, choices=[('CORRECTIVO', 'Correctivo'), ('PREVENTIVO', 'Preventivo (Motor)'), ('THERMO', 'Mantenimiento Thermo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='flota.unidad', verbose_name='Unidad'),
        ),
    ]
