# Generated by Django 5.2.7 on 2026-05-28 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagramas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramaCompartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(choices=[('ver', 'Solo ver'), ('editar', 'Puede editar')], default='ver', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('compartido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagramas_que_compartio', to=settings.AUTH_USER_MODEL)),
                ('diagrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartidos', to='diagramas.diagrama')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagramas_compartidos_conmigo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
                'unique_together': {('diagrama', 'usuario')},
            },
        ),
    ]
