# Generated by Django 5.2.7 on 2026-05-28 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagramas', '0002_diagramacompartido'),
        ('modulos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramaAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('ENVIO', 'Envio a aprobacion'), ('APROBAR', 'Aprobado'), ('RECHAZAR', 'Rechazado'), ('VINCULAR', 'Vinculado a modulo'), ('DESVINCULAR', 'Desvinculado de modulo')], max_length=15)),
                ('comentario', models.CharField(blank=True, max_length=600)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='diagrama',
            name='aprobador',
            field=models.ForeignKey(blank=True, help_text='Usuario designado para aprobar el diagrama actual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagramas_a_aprobar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagrama',
            name='comentario_decision',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='diagrama',
            name='decidido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagrama',
            name='decidido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagramas_decididos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagrama',
            name='enviado_aprobacion_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagrama',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revision'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='BORRADOR', max_length=15),
        ),
        migrations.AddField(
            model_name='diagrama',
            name='modulo_vinculado',
            field=models.ForeignKey(blank=True, help_text='Si esta vinculado a un modulo, los usuarios con acceso al modulo veran este diagrama.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagramas_vinculados', to='modulos.modulo'),
        ),
        migrations.AddIndex(
            model_name='diagrama',
            index=models.Index(fields=['estado', 'modulo_vinculado'], name='diagramas_d_estado_4474f3_idx'),
        ),
        migrations.AddField(
            model_name='diagramaaprobacion',
            name='aprobador_destinado',
            field=models.ForeignKey(blank=True, help_text='Cuando accion=ENVIO, a quien se le solicito aprobar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagramaaprobacion',
            name='diagrama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_aprobacion', to='diagramas.diagrama'),
        ),
        migrations.AddField(
            model_name='diagramaaprobacion',
            name='modulo',
            field=models.ForeignKey(blank=True, help_text='Si accion=VINCULAR/DESVINCULAR, modulo involucrado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='modulos.modulo'),
        ),
        migrations.AddField(
            model_name='diagramaaprobacion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagramas_acciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
