# Generated by Django 5.2.7 on 2026-05-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagramas', '0003_diagramaaprobacion_diagrama_aprobador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagrama',
            name='visto_por_aprobador_en',
            field=models.DateTimeField(blank=True, help_text='Primera vez que el aprobador designado abrio el diagrama en revision.', null=True),
        ),
        migrations.AlterField(
            model_name='diagramaaprobacion',
            name='accion',
            field=models.CharField(choices=[('ENVIO', 'Envio a aprobacion'), ('VISTO', 'Visto por el aprobador'), ('APROBAR', 'Aprobado'), ('RECHAZAR', 'Rechazado'), ('VINCULAR', 'Vinculado a modulo'), ('DESVINCULAR', 'Desvinculado de modulo')], max_length=15),
        ),
    ]
