# Generated by Django 5.2.7 on 2026-05-26 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Autotransporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placas", models.CharField(max_length=20)),
                ("anio_modelo", models.PositiveIntegerField()),
                (
                    "config_vehicular",
                    models.CharField(
                        help_text="Clave SAT c_ConfigAutotransporte", max_length=6
                    ),
                ),
                (
                    "permiso_sct",
                    models.CharField(
                        help_text="Clave SAT c_TipoPermiso", max_length=10
                    ),
                ),
                ("numero_permiso", models.CharField(max_length=50)),
                (
                    "aseguradora_resp_civil",
                    models.CharField(blank=True, max_length=200),
                ),
                ("poliza_resp_civil", models.CharField(blank=True, max_length=80)),
                (
                    "aseguradora_med_ambiente",
                    models.CharField(blank=True, max_length=200),
                ),
                ("poliza_med_ambiente", models.CharField(blank=True, max_length=80)),
                ("activa", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cp_autotransportes",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["placas"],
                "unique_together": {("empresa", "placas")},
            },
        ),
        migrations.CreateModel(
            name="CartaPorte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio_interno", models.CharField(blank=True, max_length=40)),
                ("transp_internacional", models.BooleanField(default=False)),
                ("entrada_salida_merc", models.CharField(blank=True, max_length=10)),
                ("pais_origen_destino", models.CharField(blank=True, max_length=4)),
                ("via_entrada_salida", models.CharField(blank=True, max_length=4)),
                (
                    "total_distancia_rec",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("fecha_traslado", models.DateTimeField()),
                ("notas", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("TIMBRADO", "Timbrado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="BORRADOR",
                        max_length=15,
                    ),
                ),
                ("folio_fiscal", models.CharField(blank=True, max_length=64)),
                (
                    "xml",
                    models.FileField(
                        blank=True, null=True, upload_to="cartaporte/xml/"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="cartaporte/pdf/"
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "autotransporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cartas_porte",
                        to="carta_porte.autotransporte",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartas_porte",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="Mercancia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bienes_transp",
                    models.CharField(help_text="ClaveProdServCP", max_length=15),
                ),
                ("descripcion", models.CharField(max_length=400)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                ("clave_unidad", models.CharField(max_length=6)),
                (
                    "peso_kg",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "valor_mercancia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("moneda", models.CharField(default="MXN", max_length=3)),
                ("material_peligroso", models.BooleanField(default=False)),
                (
                    "clave_material_peligroso",
                    models.CharField(blank=True, max_length=10),
                ),
                ("embalaje", models.CharField(blank=True, max_length=10)),
                ("descripcion_embalaje", models.CharField(blank=True, max_length=200)),
                ("dimensiones", models.CharField(blank=True, max_length=80)),
                ("fraccion_arancelaria", models.CharField(blank=True, max_length=15)),
                (
                    "carta_porte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mercancias",
                        to="carta_porte.cartaporte",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Operador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfc", models.CharField(max_length=13)),
                ("nombre", models.CharField(max_length=200)),
                ("licencia", models.CharField(max_length=40)),
                ("codigo_postal", models.CharField(blank=True, max_length=10)),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cp_operadores",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
                "unique_together": {("empresa", "rfc")},
            },
        ),
        migrations.AddField(
            model_name="cartaporte",
            name="operador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cartas_porte",
                to="carta_porte.operador",
            ),
        ),
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("rfc", models.CharField(default="XAXX010101000", max_length=13)),
                ("codigo_postal", models.CharField(max_length=10)),
                ("estado", models.CharField(max_length=4)),
                ("municipio", models.CharField(blank=True, max_length=6)),
                ("colonia", models.CharField(blank=True, max_length=10)),
                ("calle", models.CharField(blank=True, max_length=200)),
                ("numero_exterior", models.CharField(blank=True, max_length=20)),
                ("numero_interior", models.CharField(blank=True, max_length=20)),
                ("referencia", models.CharField(blank=True, max_length=200)),
                ("activa", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cp_ubicaciones",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["empresa", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="CartaPorteUbicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("Origen", "Origen"), ("Destino", "Destino")],
                        max_length=10,
                    ),
                ),
                (
                    "id_ubicacion",
                    models.CharField(help_text="OR000001 / DE000001", max_length=10),
                ),
                ("fecha_hora", models.DateTimeField()),
                (
                    "distancia_recorrida",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                (
                    "carta_porte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ubicaciones_cp",
                        to="carta_porte.cartaporte",
                    ),
                ),
                (
                    "ubicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="carta_porte.ubicacion",
                    ),
                ),
            ],
            options={
                "ordering": ["carta_porte", "orden"],
            },
        ),
    ]
