# Generated by Django 5.2.8 on 2026-06-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta_porte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='licencia_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
