# Generated by Django 5.2.8 on 2026-06-06 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta_porte', '0002_operador_licencia_vencimiento'),
        ('rh', '0005_empleado_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores', to='rh.empleado'),
        ),
    ]
