# Generated by Django 5.2.7 on 2026-05-26 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departamentos",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "unique_together": {("empresa", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_empleado", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=200)),
                ("rfc", models.CharField(blank=True, max_length=13)),
                ("curp", models.CharField(blank=True, max_length=18)),
                ("nss", models.CharField(blank=True, max_length=15)),
                ("fecha_ingreso", models.DateField()),
                ("fecha_baja", models.DateField(blank=True, null=True)),
                ("motivo_baja", models.CharField(blank=True, max_length=200)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.CharField(blank=True, max_length=300)),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empleados",
                        to="core.empresa",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.sucursal",
                    ),
                ),
                (
                    "user_sistema",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empleado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_otorgamiento", models.DateField()),
                ("cuotas", models.PositiveIntegerField(default=1)),
                (
                    "descuento_por_cuota",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=12)),
                ("estado", models.CharField(default="ACTIVO", max_length=15)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestamos",
                        to="rh.empleado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Puesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                (
                    "salario_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="puestos",
                        to="rh.departamento",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puestos",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "unique_together": {("empresa", "nombre")},
            },
        ),
        migrations.AddField(
            model_name="empleado",
            name="puesto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="empleados",
                to="rh.puesto",
            ),
        ),
        migrations.CreateModel(
            name="Vacacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("dias", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEND", "Pendiente"),
                            ("APROB", "Aprobada"),
                            ("TOMADA", "Tomada"),
                            ("CANC", "Cancelada"),
                        ],
                        default="PEND",
                        max_length=15,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacaciones",
                        to="rh.empleado",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="empleado",
            unique_together={("empresa", "numero_empleado")},
        ),
    ]
