# Generated by Django 5.2.7 on 2026-05-27 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("rh", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoSolicitudRH",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("PERMISO", "Permiso"),
                            ("VACACION", "Vacacion"),
                            ("PRESTAMO", "Prestamo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
                ("color", models.CharField(default="#3B82F6", max_length=9)),
                (
                    "icono",
                    models.CharField(
                        default="FileText",
                        help_text="Nombre del icono lucide-react",
                        max_length=40,
                    ),
                ),
                (
                    "requiere_documento",
                    models.BooleanField(
                        default=False,
                        help_text="Si esta marcado, el empleado debe adjuntar un archivo (incapacidad, etc.)",
                    ),
                ),
                (
                    "dias_maximos",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tope de dias permitidos por solicitud (opcional)",
                        null=True,
                    ),
                ),
                ("con_goce_sueldo", models.BooleanField(default=True)),
                ("requiere_aprobacion", models.BooleanField(default=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_solicitud_rh",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de solicitud RH",
                "verbose_name_plural": "Tipos de solicitud RH",
                "ordering": ["empresa", "categoria", "nombre"],
                "unique_together": {("empresa", "categoria", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="SolicitudRH",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("dias", models.PositiveIntegerField(default=0)),
                (
                    "monto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("cuotas", models.PositiveIntegerField(blank=True, null=True)),
                ("motivo", models.TextField(blank=True)),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        help_text="Adjunto (justificante, incapacidad, etc.) si lo requiere el tipo",
                        null=True,
                        upload_to="rh/solicitudes/",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEND", "Pendiente"),
                            ("APROB", "Aprobada"),
                            ("RECH", "Rechazada"),
                            ("CANC", "Cancelada"),
                        ],
                        default="PEND",
                        max_length=10,
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                (
                    "comentarios_aprobacion",
                    models.TextField(
                        blank=True,
                        help_text="Comentarios del staff al aprobar / rechazar",
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rh_solicitudes_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes",
                        to="rh.empleado",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_rh",
                        to="core.empresa",
                    ),
                ),
                (
                    "solicitado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rh_solicitudes_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes",
                        to="rh.tiposolicitudrh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud RH",
                "verbose_name_plural": "Solicitudes RH",
                "ordering": ["-fecha_solicitud"],
            },
        ),
    ]
