# Generated by Django 5.2.7 on 2026-05-27 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("rh", "0002_tiposolicitudrh_solicitudrh"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigNotificacionRH",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_notif_rh",
                        to="core.empresa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_notif_rh",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuracion de notificaciones RH",
                "verbose_name_plural": "Configuracion de notificaciones RH",
                "unique_together": {("empresa", "user")},
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SOL_NUEVA", "Nueva solicitud"),
                            ("SOL_APROB", "Solicitud aprobada"),
                            ("SOL_RECH", "Solicitud rechazada"),
                            ("SOL_CANC", "Solicitud cancelada"),
                            ("INFO", "Informacion"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField(blank=True)),
                (
                    "enlace",
                    models.CharField(
                        blank=True,
                        help_text="Ruta del frontend a abrir (p.ej. /rh/permisos)",
                        max_length=300,
                    ),
                ),
                ("leida", models.BooleanField(default=False)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("leida_en", models.DateTimeField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="core.empresa",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notificaciones",
                        to="rh.solicitudrh",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado"],
                "indexes": [
                    models.Index(
                        fields=["user", "leida", "-creado"],
                        name="rh_notifica_user_id_c6a40d_idx",
                    )
                ],
            },
        ),
    ]
