# Generated by Django 5.2.7 on 2026-05-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0003_confignotificacionrh_notificacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="banco_clave",
            field=models.CharField(blank=True, help_text="c_Banco SAT", max_length=4),
        ),
        migrations.AddField(
            model_name="empleado",
            name="clabe_interbancaria",
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name="empleado",
            name="clave_entidad_federativa",
            field=models.CharField(
                blank=True, help_text="c_Estado donde labora (ej: NLE).", max_length=4
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="codigo_postal_fiscal",
            field=models.CharField(
                blank=True,
                help_text="CP fiscal (debe coincidir con Constancia Fiscal). Va en el receptor.",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="cuenta_bancaria",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="empleado",
            name="numero_tarjeta",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="empleado",
            name="periodicidad_pago",
            field=models.CharField(
                blank=True,
                default="04",
                help_text="c_PeriodicidadPago. 04 Quincenal por defecto.",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="regimen_fiscal",
            field=models.CharField(
                blank=True,
                default="605",
                help_text="c_RegimenFiscal. 605 Sueldos por defecto.",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="riesgo_puesto",
            field=models.CharField(
                blank=True, help_text="c_RiesgoPuesto. 1..5 grados.", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="salario_base_cotizacion",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="SBC: para calculo IMSS",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="salario_diario",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="empleado",
            name="salario_diario_integrado",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="SDI: incluye factor de prestaciones de ley",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="sindicalizado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empleado",
            name="sueldo_neto_mensual",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Solo informativo / referencia.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="tipo_contrato",
            field=models.CharField(
                blank=True,
                help_text="c_TipoContrato. Ej: 01 Indeterminado.",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="tipo_jornada",
            field=models.CharField(
                blank=True, help_text="c_TipoJornada. Ej: 01 Diurna.", max_length=4
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="tipo_regimen",
            field=models.CharField(
                blank=True,
                default="02",
                help_text="c_TipoRegimen. Ej: 02 Sueldos.",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="uso_cfdi",
            field=models.CharField(
                blank=True,
                default="CN01",
                help_text="c_UsoCFDI. CN01 Nomina por defecto.",
                max_length=4,
            ),
        ),
    ]
