# Generated by Django 5.2.7 on 2026-05-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0004_empleado_banco_clave_empleado_clabe_interbancaria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="apellido",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
