# Generated by Django 5.2.7 on 2026-05-26 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_comercial", models.CharField(max_length=200)),
                ("razon_social", models.CharField(max_length=255)),
                ("rfc", models.CharField(max_length=13, unique=True)),
                (
                    "regimen_fiscal",
                    models.CharField(
                        blank=True, help_text="Clave SAT del regimen", max_length=10
                    ),
                ),
                ("cp_fiscal", models.CharField(blank=True, max_length=10)),
                ("direccion", models.CharField(blank=True, max_length=300)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="empresas/logos/"
                    ),
                ),
                ("color_primario", models.CharField(default="#1A73E8", max_length=9)),
                ("color_secundario", models.CharField(default="#34A853", max_length=9)),
                ("activa", models.BooleanField(default=True)),
                ("creada", models.DateTimeField(auto_now_add=True)),
                ("actualizada", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nombre_comercial"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pac_proveedor",
                    models.CharField(
                        choices=[
                            ("facturacom", "Factura.com"),
                            ("manual", "Sin PAC (manual)"),
                        ],
                        default="facturacom",
                        max_length=30,
                    ),
                ),
                (
                    "pac_base_url",
                    models.URLField(blank=True, default="https://api.factura.com"),
                ),
                ("pac_api_key", models.CharField(blank=True, max_length=255)),
                ("pac_secret_key", models.CharField(blank=True, max_length=255)),
                (
                    "pac_plugin",
                    models.CharField(blank=True, default="9", max_length=10),
                ),
                ("pac_sandbox", models.BooleanField(default=False)),
                ("emisor_rfc", models.CharField(blank=True, max_length=13)),
                ("emisor_nombre", models.CharField(blank=True, max_length=255)),
                ("emisor_regimen", models.CharField(blank=True, max_length=10)),
                ("emisor_cp", models.CharField(blank=True, max_length=10)),
                ("moneda_default", models.CharField(default="MXN", max_length=3)),
                ("forma_pago_default", models.CharField(default="99", max_length=5)),
                ("metodo_pago_default", models.CharField(default="PUE", max_length=5)),
                ("uso_cfdi_default", models.CharField(default="S01", max_length=5)),
                ("requiere_carta_porte", models.BooleanField(default=False)),
                ("permite_facturacion", models.BooleanField(default=True)),
                ("notificaciones_email", models.BooleanField(default=False)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="core.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificadoCSD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_certificado", models.CharField(blank=True, max_length=20)),
                ("archivo_cer", models.FileField(upload_to="csd/cer/")),
                ("archivo_key", models.FileField(upload_to="csd/key/")),
                (
                    "password_csd",
                    models.CharField(
                        help_text="Contrasena del .key (almacenar cifrado en prod)",
                        max_length=255,
                    ),
                ),
                ("vigente_desde", models.DateField(blank=True, null=True)),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("subido", models.DateTimeField(auto_now_add=True)),
                (
                    "subido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["-subido"],
            },
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=150)),
                ("direccion", models.CharField(blank=True, max_length=300)),
                ("cp", models.CharField(blank=True, max_length=10)),
                ("activa", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sucursales",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["empresa", "nombre"],
                "unique_together": {("empresa", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("puesto", models.CharField(blank=True, max_length=120)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="usuarios/avatar/"
                    ),
                ),
                (
                    "tema",
                    models.CharField(
                        choices=[("dark", "Oscuro"), ("light", "Claro")],
                        default="dark",
                        max_length=10,
                    ),
                ),
                ("fuente", models.CharField(default="system", max_length=20)),
                ("color_acento", models.CharField(default="#1A73E8", max_length=9)),
                (
                    "empresa_activa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios_activos",
                        to="core.empresa",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sucursal_activa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.sucursal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("OWNER", "Propietario"),
                            ("STAFF", "Staff (administrador)"),
                            ("MANAGER", "Gerente"),
                            ("USER", "Usuario"),
                            ("READONLY", "Solo lectura"),
                        ],
                        default="USER",
                        max_length=15,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miembros",
                        to="core.empresa",
                    ),
                ),
                ("sucursales", models.ManyToManyField(blank=True, to="core.sucursal")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["empresa", "user__username"],
                "unique_together": {("user", "empresa")},
            },
        ),
    ]
