# Generated by Django 5.2.8 on 2026-06-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='pac_serie_cp_id',
            field=models.CharField(blank=True, help_text='ID de la serie de Carta Porte (Traslado) en Factura.com', max_length=40),
        ),
    ]
