# Generated by Django 5.2.7 on 2026-05-28 18:11

import apps.gestion_documental.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('rh', '0005_empleado_apellido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlujoAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=400)),
                ('modo', models.CharField(choices=[('UNICO', 'Un solo aprobador'), ('PARALELO', 'Aprobadores en paralelo'), ('SECUENCIAL', 'Aprobadores en orden (secuencial)')], default='UNICO', max_length=12)),
                ('min_aprobaciones', models.PositiveIntegerField(default=1, help_text='Solo aplica en modo PARALELO. Cuantas firmas se necesitan.')),
                ('activo', models.BooleanField(default=True)),
                ('es_default', models.BooleanField(default=False, help_text='Si es True, este flujo se usa por defecto para su tipo de documento.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujos_aprobacion', to='core.empresa')),
            ],
            options={
                'ordering': ['empresa', 'tipo_documento', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Codigo unico del documento. Ej. 'PR-RH-001'.", max_length=40)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revision'), ('VIGENTE', 'Vigente'), ('OBSOLETO', 'Obsoleto'), ('RECHAZADO', 'Rechazado')], db_index=True, default='BORRADOR', max_length=15)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=apps.gestion_documental.models.documento_upload_to)),
                ('archivo_nombre_original', models.CharField(blank=True, max_length=300)),
                ('archivo_mime', models.CharField(blank=True, max_length=120)),
                ('archivo_tamano', models.PositiveBigIntegerField(default=0)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_proxima_revision', models.DateField(blank=True, help_text='Cuando se debe revisar este doc. ISO 9001 recomienda revisiones periodicas.', null=True)),
                ('fecha_obsolescencia', models.DateField(blank=True, null=True)),
                ('etiquetas', models.CharField(blank=True, help_text='Separadas por coma. Para busqueda.', max_length=400)),
                ('palabras_clave', models.CharField(blank=True, max_length=400)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('visible_para_todos', models.BooleanField(default=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_creados', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='rh.departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.empresa')),
                ('flujo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='gestion_documental.flujoaprobacion')),
            ],
            options={
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('archivo_propuesto', models.FileField(blank=True, null=True, upload_to=apps.gestion_documental.models.propuesta_upload_to)),
                ('archivo_nombre_original', models.CharField(blank=True, max_length=300)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('RETIRADA', 'Retirada')], db_index=True, default='PENDIENTE', max_length=12)),
                ('comentario_revision', models.CharField(blank=True, max_length=600)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_mejora', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='gestion_documental.documento')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=12)),
                ('comentario_envio', models.CharField(blank=True, max_length=600)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='gestion_documental.documento')),
                ('enviada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_doc_enviadas', to=settings.AUTH_USER_MODEL)),
                ('flujo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='gestion_documental.flujoaprobacion')),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('POLITICA', 'Politica'), ('MANUAL', 'Manual'), ('PROCEDIMIENTO', 'Procedimiento'), ('INSTRUCTIVO', 'Instructivo'), ('FORMATO', 'Formato'), ('REGISTRO', 'Registro'), ('PLAN', 'Plan'), ('OTRO', 'Otro')], default='PROCEDIMIENTO', max_length=20)),
                ('codigo', models.CharField(help_text="Prefijo corto. Ej. 'PR' para procedimientos, 'IT' para instructivos.", max_length=10)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=400)),
                ('color', models.CharField(default='#3B82F6', max_length=9)),
                ('icono', models.CharField(default='FileText', max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_documento', to='core.empresa')),
            ],
            options={
                'ordering': ['empresa', 'categoria', 'codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='flujoaprobacion',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, help_text='Si esta vacio, es un flujo generico que el usuario puede elegir manualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flujos', to='gestion_documental.tipodocumento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='gestion_documental.tipodocumento'),
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('archivo', models.FileField(upload_to=apps.gestion_documental.models.version_upload_to)),
                ('archivo_nombre_original', models.CharField(blank=True, max_length=300)),
                ('archivo_mime', models.CharField(blank=True, max_length=120)),
                ('archivo_tamano', models.PositiveBigIntegerField(default=0)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('notas_cambios', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='gestion_documental.documento')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='AccesoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver', models.BooleanField(default=True)),
                ('puede_descargar', models.BooleanField(default=True)),
                ('puede_proponer_mejora', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('otorgado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_otorgados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_documentos', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='gestion_documental.documento')),
            ],
            options={
                'ordering': ['-creado'],
                'unique_together': {('documento', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='PasoFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('obligatorio', models.BooleanField(default=True, help_text='Si False, el flujo puede avanzar sin este aprobador (modo paralelo).')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('aprobador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_flujo', to=settings.AUTH_USER_MODEL)),
                ('flujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='gestion_documental.flujoaprobacion')),
            ],
            options={
                'ordering': ['flujo', 'orden'],
                'unique_together': {('flujo', 'aprobador')},
            },
        ),
        migrations.CreateModel(
            name='PasoAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('obligatorio', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('OMITIDO', 'Omitido')], db_index=True, default='PENDIENTE', max_length=12)),
                ('comentario', models.CharField(blank=True, max_length=600)),
                ('decidido_en', models.DateTimeField(blank=True, null=True)),
                ('aprobador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasos_aprobacion', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='gestion_documental.solicitudaprobacion')),
            ],
            options={
                'ordering': ['solicitud', 'orden'],
                'unique_together': {('solicitud', 'aprobador')},
            },
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['empresa', 'estado'], name='gestion_doc_empresa_c2e9eb_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['empresa', 'tipo'], name='gestion_doc_empresa_83ebfa_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['codigo'], name='gestion_doc_codigo_aa6381_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='versiondocumento',
            unique_together={('documento', 'version')},
        ),
    ]
