# Generated by Django 5.2.7 on 2026-06-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='contenido',
            field=models.TextField(blank=True),
        ),
    ]
