# Generated by Django 5.2.7 on 2026-05-26 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.SlugField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("OPERATIVO", "Centro Operativo"),
                            ("LOGISTICA", "Logistica y Recursos"),
                            ("RH", "Recursos Humanos"),
                            ("FINANZAS", "Inteligencia y Finanzas"),
                            ("ADMIN", "Administracion"),
                            ("CATALOGOS", "Catalogos"),
                            ("HERRAMIENTAS", "Herramientas"),
                        ],
                        default="ADMIN",
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(default="#1A73E8", max_length=9)),
                (
                    "icono",
                    models.CharField(
                        default="LayoutDashboard",
                        help_text="Nombre del icono lucide-react para el frontend",
                        max_length=40,
                    ),
                ),
                ("ruta_frontend", models.CharField(default="/", max_length=120)),
                ("orden", models.PositiveIntegerField(default=100)),
                ("requiere_staff", models.BooleanField(default=False)),
                ("requiere_carta_porte", models.BooleanField(default=False)),
                (
                    "es_core",
                    models.BooleanField(
                        default=False, help_text="Modulos core no se pueden desactivar"
                    ),
                ),
                ("activo_globalmente", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["categoria", "orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="AccionModulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("read", "Lectura"),
                            ("create", "Crear"),
                            ("update", "Editar"),
                            ("delete", "Eliminar"),
                            ("export", "Exportar"),
                            ("admin", "Administrar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acciones",
                        to="modulos.modulo",
                    ),
                ),
            ],
            options={
                "ordering": ["modulo", "codigo"],
                "unique_together": {("modulo", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="AsignacionModulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "acciones",
                    models.ManyToManyField(blank=True, to="modulos.accionmodulo"),
                ),
                (
                    "asignado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asignaciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_modulo",
                        to="core.empresa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_modulo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="modulos.modulo",
                    ),
                ),
            ],
            options={
                "ordering": ["empresa", "user__username", "modulo__nombre"],
                "unique_together": {("user", "empresa", "modulo")},
            },
        ),
        migrations.CreateModel(
            name="ModuloEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Config especifica del modulo en esta empresa",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "activado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modulos_activados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modulos",
                        to="core.empresa",
                    ),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresas",
                        to="modulos.modulo",
                    ),
                ),
            ],
            options={
                "ordering": ["empresa", "modulo"],
                "unique_together": {("empresa", "modulo")},
            },
        ),
    ]
