# Generated by Django 5.2.7 on 2026-05-26 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SatClaveUnidad",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("simbolo", models.CharField(blank=True, max_length=30)),
                ("descripcion", models.CharField(blank=True, max_length=400)),
            ],
            options={
                "ordering": ["clave"],
            },
        ),
        migrations.CreateModel(
            name="SatCodigoPostal",
            fields=[
                (
                    "codigo_postal",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("estado", models.CharField(blank=True, max_length=4)),
                ("municipio", models.CharField(blank=True, max_length=6)),
                ("localidad", models.CharField(blank=True, max_length=4)),
            ],
            options={
                "ordering": ["codigo_postal"],
            },
        ),
        migrations.CreateModel(
            name="SatConfigVehicular",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=300)),
                ("remolque", models.BooleanField(default=False)),
                ("semirremolque", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SatEstado",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("pais", models.CharField(default="MEX", max_length=4)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="SatFormaPago",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="SatMaterialPeligroso",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=400)),
                ("clase_division", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="SatMetodoPago",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="SatMoneda",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("decimales", models.PositiveSmallIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name="SatRegimenFiscal",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=300)),
                ("fisica", models.BooleanField(default=True)),
                ("moral", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SatTipoEmbalaje",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="SatTipoFigura",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SatTipoPermiso",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="SatUsoCFDI",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=300)),
                ("aplica_fisica", models.BooleanField(default=True)),
                ("aplica_moral", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SatClaveProdServ",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=600)),
                ("incluye_iva", models.CharField(blank=True, max_length=2)),
                ("palabras_similares", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["clave"],
                "indexes": [
                    models.Index(
                        fields=["descripcion"], name="catalogos_s_descrip_656ead_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SatClaveProdServCP",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=600)),
                ("material_peligroso", models.CharField(blank=True, max_length=10)),
                ("embalaje", models.CharField(blank=True, max_length=10)),
                ("descripcion_embalaje", models.CharField(blank=True, max_length=400)),
            ],
            options={
                "ordering": ["clave"],
                "indexes": [
                    models.Index(
                        fields=["descripcion"], name="catalogos_s_descrip_52e4d4_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SatColonia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_postal", models.CharField(db_index=True, max_length=10)),
                ("clave", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=300)),
            ],
            options={
                "ordering": ["codigo_postal", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["codigo_postal", "nombre"],
                        name="catalogos_s_codigo__6dc8f0_idx",
                    )
                ],
                "unique_together": {("codigo_postal", "clave")},
            },
        ),
        migrations.CreateModel(
            name="SatMunicipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=6)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="municipios",
                        to="catalogos_sat.satestado",
                    ),
                ),
            ],
            options={
                "ordering": ["estado", "nombre"],
                "unique_together": {("estado", "clave")},
            },
        ),
    ]
