# Generated by Django 5.2.7 on 2026-05-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos_sat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SatSubTipoRem",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=300)),
            ],
        ),
    ]
