# Generated by Django 5.2.7 on 2026-05-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos_sat", "0002_satsubtiporem"),
    ]

    operations = [
        migrations.CreateModel(
            name="SatBanco",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("razon_social", models.CharField(max_length=300)),
                ("nombre_corto", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SatPeriodicidadPago",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SatRiesgoPuesto",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SatTipoContrato",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SatTipoDeduccion",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SatTipoIncapacidad",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SatTipoJornada",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SatTipoNomina",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SatTipoOtroPago",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SatTipoPercepcion",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("es_exento_parcial", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SatTipoRegimen",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
    ]
