# Generated by Django 5.2.7 on 2026-05-26 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carta_porte", "0001_initial"),
        ("core", "0001_initial"),
        ("viajes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquidacionOperador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.CharField(max_length=40)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("total_viajes", models.PositiveIntegerField(default=0)),
                (
                    "monto_viajes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "bonos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "descuentos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("APROBADA", "Aprobada"),
                            ("PAGADA", "Pagada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="BORRADOR",
                        max_length=15,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidaciones",
                        to="core.empresa",
                    ),
                ),
                (
                    "operador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones",
                        to="carta_porte.operador",
                    ),
                ),
            ],
            options={
                "unique_together": {("empresa", "folio")},
            },
        ),
        migrations.CreateModel(
            name="ConceptoLiquidacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("BONO", "Bono"),
                            ("DESC", "Descuento"),
                            ("VIAJE", "Viaje"),
                        ],
                        max_length=10,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "viaje",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="viajes.viaje",
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conceptos",
                        to="liquidaciones.liquidacionoperador",
                    ),
                ),
            ],
        ),
    ]
