# Generated by Django 5.2.7 on 2026-05-26 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=40)),
                ("placas", models.CharField(blank=True, max_length=20)),
                ("marca", models.CharField(blank=True, max_length=80)),
                ("modelo", models.CharField(blank=True, max_length=80)),
                ("anio", models.PositiveIntegerField(blank=True, null=True)),
                ("tipo", models.CharField(blank=True, max_length=40)),
                ("vin", models.CharField(blank=True, max_length=40)),
                (
                    "capacidad_carga_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "km_actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["empresa", "numero"],
                "unique_together": {("empresa", "numero")},
            },
        ),
        migrations.CreateModel(
            name="CargaCombustible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("litros", models.DecimalField(decimal_places=3, max_digits=10)),
                ("precio_litro", models.DecimalField(decimal_places=4, max_digits=10)),
                ("importe", models.DecimalField(decimal_places=2, max_digits=12)),
                ("km_actual", models.DecimalField(decimal_places=2, max_digits=12)),
                ("estacion", models.CharField(blank=True, max_length=120)),
                ("folio", models.CharField(blank=True, max_length=40)),
                (
                    "unidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargas",
                        to="flota.unidad",
                    ),
                ),
            ],
        ),
    ]
