# Generated by Django 5.2.7 on 2026-05-26 22:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flota", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cargacombustible",
            options={"ordering": ["-fecha"]},
        ),
        migrations.AddField(
            model_name="cargacombustible",
            name="notas",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="cargacombustible",
            name="rendimiento_kml",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0,
                help_text="Rendimiento calculado al momento de la carga (km/L)",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="cargacombustible",
            name="ticket_foto",
            field=models.ImageField(blank=True, null=True, upload_to="flota/tickets/"),
        ),
        migrations.AddField(
            model_name="unidad",
            name="actualizado",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="unidad",
            name="aseguradora_carga",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="unidad",
            name="aseguradora_med_ambiente",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="unidad",
            name="aseguradora_resp_civil",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="unidad",
            name="capacidad_combustible_litros",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="unidad",
            name="color",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="unidad",
            name="config_vehicular",
            field=models.CharField(
                blank=True,
                help_text="Clave SAT c_ConfigAutotransporte (ej. C2, T3S2, T3S3)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="unidad",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unidad",
            name="fecha_adquisicion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidad",
            name="fecha_baja",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidad",
            name="fecha_revista_vence",
            field=models.DateField(
                blank=True,
                help_text="Vigencia de la revista mecanica federal",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unidad",
            name="fecha_seguro_vence",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidad",
            name="fecha_tarjeta_circulacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidad",
            name="fecha_verificacion_vence",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidad",
            name="motivo_baja",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="unidad",
            name="notas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unidad",
            name="numero_permiso_sct",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="unidad",
            name="permiso_sct",
            field=models.CharField(
                blank=True,
                help_text="Clave SAT c_TipoPermiso (TPAF01-13)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="unidad",
            name="peso_bruto_vehicular",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Peso Bruto Vehicular en toneladas (PBV)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="unidad",
            name="poliza_carga",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="unidad",
            name="poliza_med_ambiente",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="unidad",
            name="poliza_resp_civil",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="unidad",
            name="prima_seguro_carga",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="unidad",
            name="proveedor_compra",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="unidad",
            name="remolque1_placa",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="unidad",
            name="remolque1_subtipo",
            field=models.CharField(
                blank=True,
                help_text="Clave SAT c_SubTipoRem para el primer remolque",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="unidad",
            name="remolque2_placa",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="unidad",
            name="remolque2_subtipo",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="unidad",
            name="rendimiento_promedio_kml",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="km/L promedio historico para deteccion de anomalias",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="unidad",
            name="tipo_combustible",
            field=models.CharField(
                choices=[
                    ("DIESEL", "Diesel"),
                    ("GASOLINA", "Gasolina"),
                    ("GAS_LP", "Gas LP"),
                    ("GAS_NATURAL", "Gas natural"),
                    ("HIBRIDO", "Hibrido"),
                    ("ELECTRICO", "Electrico"),
                    ("OTRO", "Otro"),
                ],
                default="DIESEL",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="unidad",
            name="valor_factura",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="unidad",
            name="anio",
            field=models.PositiveIntegerField(
                blank=True, help_text="Anio modelo", null=True
            ),
        ),
        migrations.AlterField(
            model_name="unidad",
            name="capacidad_carga_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Capacidad de carga util en kg",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="unidad",
            name="numero",
            field=models.CharField(help_text="Numero economico interno", max_length=40),
        ),
        migrations.AlterField(
            model_name="unidad",
            name="tipo",
            field=models.CharField(
                blank=True,
                help_text="Tractor, caja seca, plataforma, etc.",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="unidad",
            name="vin",
            field=models.CharField(
                blank=True, help_text="NIV / VIN del vehiculo", max_length=40
            ),
        ),
    ]
