# Generated by Django 5.2.7 on 2026-05-30 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('flota', '0002_alter_cargacombustible_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='termo_fijo',
            field=models.BooleanField(default=False, help_text='El termo va fijo/asignado permanentemente a esta unidad.'),
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Numero economico del termo', max_length=40)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('serie', models.CharField(blank=True, max_length=80)),
                ('horas_actual', models.DecimalField(decimal_places=2, default=0, help_text='Horometro actual del termo', max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos', to='core.empresa')),
            ],
            options={
                'ordering': ['empresa', 'numero'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='unidad',
            name='termo',
            field=models.ForeignKey(blank=True, help_text='Termo asignado a la unidad (cuando es fijo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='flota.termo'),
        ),
    ]
