# Generated by Django 5.2.7 on 2026-05-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0003_unidad_termo_fijo_termo_unidad_termo'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='fecha_ultimo_servicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termo',
            name='horas_ultimo_servicio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horometro al momento del ultimo servicio (base)', max_digits=12),
        ),
        migrations.AddField(
            model_name='termo',
            name='intervalo_horas_preventivo',
            field=models.DecimalField(decimal_places=2, default=1200, help_text='Horas entre servicios preventivos', max_digits=12),
        ),
        migrations.AddField(
            model_name='unidad',
            name='fecha_ultimo_servicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='intervalo_km_preventivo',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Km entre servicios preventivos de motor', max_digits=12),
        ),
        migrations.AddField(
            model_name='unidad',
            name='km_ultimo_servicio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Odometro al momento del ultimo servicio (base)', max_digits=12),
        ),
    ]
