# Generated by Django 5.2.7 on 2026-05-26 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("almacen", "0001_initial"),
        ("flota", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenMantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.CharField(max_length=40)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PREVENTIVO", "Preventivo"),
                            ("CORRECTIVO", "Correctivo"),
                        ],
                        default="PREVENTIVO",
                        max_length=15,
                    ),
                ),
                ("fecha_programada", models.DateField()),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "km_unidad",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADA", "Programada"),
                            ("EN_PROCESO", "En proceso"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PROGRAMADA",
                        max_length=15,
                    ),
                ),
                ("diagnostico", models.TextField(blank=True)),
                (
                    "costo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_mantto",
                        to="flota.unidad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefaccionUsada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refacciones",
                        to="mantenimiento.ordenmantenimiento",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="almacen.producto",
                    ),
                ),
            ],
        ),
    ]
