# Generated by Django 5.2.7 on 2026-05-30 03:48

import apps.mantenimiento.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('mantenimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlujoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flujos_checklist_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flujos_checklist', to='core.empresa')),
                ('tecnicos', models.ManyToManyField(blank=True, help_text='Usuarios (tecnicos) que pueden llenar este flujo.', related_name='flujos_checklist_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='CampoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(blank=True, help_text='Agrupa campos como un checklist.', max_length=120)),
                ('etiqueta', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('texto', 'Texto corto'), ('parrafo', 'Texto largo'), ('numero', 'Numero'), ('booleano', 'Si / No'), ('seleccion', 'Seleccion'), ('foto', 'Foto'), ('fecha', 'Fecha')], default='texto', max_length=15)),
                ('obligatorio', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('ayuda', models.CharField(blank=True, max_length=300)),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('min_valor', models.FloatField(blank=True, null=True)),
                ('max_valor', models.FloatField(blank=True, null=True)),
                ('flujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='mantenimiento.flujochecklist')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, max_length=400)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('flujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='mantenimiento.flujochecklist')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_checklist', to='mantenimiento.ordenmantenimiento')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_checklist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ValorCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('numero', models.FloatField(blank=True, null=True)),
                ('booleano', models.BooleanField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=apps.mantenimiento.models.valor_foto_upload_to)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='mantenimiento.campochecklist')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='mantenimiento.respuestachecklist')),
            ],
            options={
                'unique_together': {('respuesta', 'campo')},
            },
        ),
    ]
