# Generated by Django 5.2.7 on 2026-05-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_flujochecklist_campochecklist_respuestachecklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campochecklist',
            name='clave',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='campochecklist',
            name='depende_de',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='campochecklist',
            name='mostrar_si',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
