# Generated by Django 5.2.7 on 2026-05-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_campochecklist_clave_campochecklist_depende_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campochecklist',
            name='foto_aplica',
            field=models.CharField(blank=True, choices=[('', 'No pedir foto'), ('siempre', 'Siempre'), ('si_si', 'Solo si responde Si'), ('si_no', 'Solo si responde No')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='campochecklist',
            name='foto_obligatoria',
            field=models.BooleanField(default=False),
        ),
    ]
