# Generated by Django 5.2.7 on 2026-05-30 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0003_unidad_termo_fijo_termo_unidad_termo'),
        ('mantenimiento', '0004_campochecklist_foto_aplica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestachecklist',
            name='termo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_checklist', to='flota.termo'),
        ),
        migrations.AddField(
            model_name='respuestachecklist',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_checklist', to='flota.unidad'),
        ),
        migrations.AlterField(
            model_name='campochecklist',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto corto'), ('parrafo', 'Texto largo'), ('numero', 'Numero'), ('booleano', 'Si / No'), ('seleccion', 'Seleccion'), ('foto', 'Foto'), ('fecha', 'Fecha'), ('unidad', 'Unidad (flota)'), ('km_unidad', 'Km de la unidad (actualiza catalogo)'), ('termo', 'Termo'), ('horas_termo', 'Horas del termo (actualiza catalogo)')], default='texto', max_length=15),
        ),
    ]
