# Generated by Django 5.2.7 on 2026-05-30 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('mantenimiento', '0005_respuestachecklist_termo_respuestachecklist_unidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(blank=True, help_text='Referencia de la corrida (ej. unidad, folio).', max_length=200)),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], db_index=True, default='EN_CURSO', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('iniciado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecuciones_iniciadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='EtapaProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(blank=True, max_length=160)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapas_proceso', to='mantenimiento.flujochecklist')),
                ('tecnicos', models.ManyToManyField(blank=True, help_text='Usuarios que llenan esta etapa.', related_name='etapas_proceso_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EtapaEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(blank=True, max_length=160)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVA', 'Activa'), ('COMPLETADA', 'Completada')], db_index=True, default='PENDIENTE', max_length=12)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_ejecucion', to='mantenimiento.flujochecklist')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_completadas', to=settings.AUTH_USER_MODEL)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='mantenimiento.ejecucionproceso')),
                ('respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapa_ejecucion', to='mantenimiento.respuestachecklist')),
                ('tecnicos', models.ManyToManyField(blank=True, related_name='etapas_ejecucion_asignadas', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.etapaproceso')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_mantto', to='core.empresa')),
            ],
            options={
                'ordering': ['-actualizado'],
            },
        ),
        migrations.AddField(
            model_name='etapaproceso',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='mantenimiento.proceso'),
        ),
        migrations.AddField(
            model_name='ejecucionproceso',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='mantenimiento.proceso'),
        ),
    ]
