# Generated by Django 5.2.7 on 2026-05-26 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoBitacora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("INFO", "Informacion"),
                            ("WARN", "Advertencia"),
                            ("ERROR", "Error"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("accion", models.CharField(db_index=True, max_length=80)),
                ("descripcion", models.CharField(blank=True, max_length=400)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("metodo", models.CharField(blank=True, max_length=10)),
                ("ruta", models.CharField(blank=True, max_length=300)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.empresa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["user", "fecha"], name="bitacora_ev_user_id_8f824d_idx"
                    ),
                    models.Index(
                        fields=["empresa", "fecha"],
                        name="bitacora_ev_empresa_2eddc6_idx",
                    ),
                ],
            },
        ),
    ]
