# Generated by Django 5.2.7 on 2026-05-26 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Almacen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=120)),
                ("direccion", models.CharField(blank=True, max_length=300)),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="almacenes",
                        to="core.empresa",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.sucursal",
                    ),
                ),
            ],
            options={
                "unique_together": {("empresa", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=40)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.CharField(blank=True, max_length=400)),
                ("unidad_medida", models.CharField(default="PZA", max_length=20)),
                (
                    "costo_promedio",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_almacen",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "unique_together": {("empresa", "sku")},
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SALIDA", "Salida"),
                            ("TRASPASO", "Traspaso"),
                            ("AJUSTE", "Ajuste"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=4, max_digits=12)),
                ("referencia", models.CharField(blank=True, max_length=80)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("nota", models.CharField(blank=True, max_length=300)),
                (
                    "almacen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="almacen.almacen",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="almacen.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "existencia",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "minimo",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "maximo",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "almacen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="almacen.almacen",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="almacen.producto",
                    ),
                ),
            ],
            options={
                "unique_together": {("almacen", "producto")},
            },
        ),
    ]
