# Generated by Django 5.2.7 on 2026-05-28 22:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BAJO_INVENTARIO', 'Bajo Inventario'), ('CADUCIDAD_PROXIMA', 'Caducidad Proxima'), ('EXCESO', 'Exceso de Inventario'), ('SIN_STOCK', 'Sin Stock'), ('PUNTO_REORDEN', 'Punto de Reorden')], max_length=25)),
                ('nivel', models.CharField(choices=[('INFO', 'Info'), ('ADVERTENCIA', 'Advertencia'), ('CRITICA', 'Critica')], default='ADVERTENCIA', max_length=15)),
                ('mensaje', models.CharField(max_length=300)),
                ('dias_restantes', models.IntegerField(blank=True, null=True)),
                ('cantidad_actual', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('umbral', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
                ('atendida_en', models.DateTimeField(blank=True, null=True)),
                ('comentario_atencion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=30)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('disponible', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('comprometido', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('en_transito', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['producto', 'almacen'],
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(db_index=True)),
                ('tipo', models.CharField(max_length=20)),
                ('subtipo', models.CharField(blank=True, max_length=30)),
                ('folio', models.CharField(max_length=30)),
                ('cantidad_entrada', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('cantidad_salida', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('importe_entrada', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('importe_salida', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('saldo_cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('saldo_costo_promedio', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('saldo_importe', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('metodo_costeo', models.CharField(default='PROMEDIO', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(db_index=True, max_length=60)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, db_index=True, null=True)),
                ('cantidad_inicial', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MarcaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=30)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('sitio_web', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(db_index=True, max_length=30)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRANSFERENCIA', 'Transferencia'), ('AJUSTE', 'Ajuste')], db_index=True, max_length=20)),
                ('subtipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('PRODUCCION', 'Produccion'), ('CONSUMO', 'Consumo'), ('MERMA', 'Merma'), ('DEVOLUCION_CLIENTE', 'Devolucion Cliente'), ('DEVOLUCION_PROVEEDOR', 'Devolucion Proveedor'), ('TRASPASO', 'Traspaso'), ('AJUSTE_FISICO', 'Ajuste Fisico'), ('INVENTARIO_INICIAL', 'Inventario Inicial'), ('OTRO', 'Otro')], max_length=30)),
                ('fecha', models.DateTimeField(db_index=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('CANCELADO', 'Cancelado'), ('EN_TRANSITO', 'En Transito'), ('RECIBIDO', 'Recibido')], db_index=True, default='BORRADOR', max_length=15)),
                ('documento_origen', models.TextField(blank=True)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('comentario', models.TextField(blank=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('cancelado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('importe', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['movimiento', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('altura', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('capacidad_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rack', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['zona', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(db_index=True, max_length=80, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADA', 'Reservada'), ('VENDIDA', 'Vendida'), ('DEFECTUOSA', 'Defectuosa'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=15)),
                ('garantia_hasta', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(db_index=True, max_length=30)),
                ('fecha_envio', models.DateTimeField()),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('EN_TRANSITO', 'En Transito'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada'), ('PARCIAL', 'Parcial')], default='BORRADOR', max_length=15)),
                ('transportista', models.CharField(blank=True, max_length=120)),
                ('guia', models.CharField(blank=True, max_length=60)),
                ('comentario', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_envio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_enviada', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('nota', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['transferencia', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=40)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('tipo', models.CharField(choices=[('BIN', 'Bin'), ('PALLET', 'Pallet'), ('CAJON', 'Cajon'), ('PISO', 'Piso')], default='BIN', max_length=20)),
                ('capacidad_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activa', models.BooleanField(default=True)),
                ('bloqueada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['almacen', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10)),
                ('nombre', models.CharField(max_length=60)),
                ('abreviatura', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('CANTIDAD', 'Cantidad'), ('PESO', 'Peso'), ('VOLUMEN', 'Volumen'), ('LONGITUD', 'Longitud'), ('TIEMPO', 'Tiempo'), ('AREA', 'Area')], default='CANTIDAD', max_length=20)),
                ('factor_conversion', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['empresa', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('RECEPCION', 'Recepcion'), ('ALMACENAMIENTO', 'Almacenamiento'), ('PICKING', 'Picking'), ('DESPACHO', 'Despacho'), ('CUARENTENA', 'Cuarentena')], default='ALMACENAMIENTO', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['almacen', 'codigo'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='producto',
        ),
        migrations.AlterModelOptions(
            name='almacen',
            options={'ordering': ['empresa', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['empresa', 'nombre']},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('empresa', 'sku')},
        ),
        migrations.AddField(
            model_name='almacen',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='almacen',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='almacen',
            name='permite_negativos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='almacen',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacenes_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='almacen',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='almacen',
            name='tipo',
            field=models.CharField(choices=[('CENTRAL', 'Central'), ('SUCURSAL', 'Sucursal'), ('TRANSITO', 'En Transito'), ('CUARENTENA', 'Cuarentena'), ('DEVOLUCIONES', 'Devoluciones'), ('VIRTUAL', 'Virtual')], default='CENTRAL', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_interno',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_estandar',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_ultimo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='dimensiones',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='producto',
            name='etiquetas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='producto',
            name='fotos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='producto',
            name='impuestos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='producto',
            name='inventario_max',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='producto',
            name='inventario_min',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='producto',
            name='manejo_caducidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='manejo_lote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='metodo_costeo',
            field=models.CharField(choices=[('PROMEDIO', 'Promedio Ponderado'), ('PEPS', 'PEPS'), ('ESTANDAR', 'Costo Estandar')], default='PROMEDIO', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='moneda',
            field=models.CharField(default='MXN', max_length=3),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='producto',
            name='punto_reorden',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='producto',
            name='serializado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('MATERIA_PRIMA', 'Materia Prima'), ('PRODUCTO_TERMINADO', 'Producto Terminado'), ('REFACCION', 'Refaccion'), ('CONSUMIBLE', 'Consumible'), ('SERVICIO', 'Servicio')], default='PRODUCTO_TERMINADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacenes', to='core.sucursal'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_almacen_v2', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('empresa', 'codigo_interno'), ('empresa', 'sku')},
        ),
        migrations.AddIndex(
            model_name='almacen',
            index=models.Index(fields=['empresa', 'activo'], name='almacen_alm_empresa_e2112e_idx'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='almacen.almacen'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='atendida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerta',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_almacen', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='almacen.producto'),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_producto', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='almacen.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='almacen.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='existencia',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='almacen.almacen'),
        ),
        migrations.AddField(
            model_name='existencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='existencia',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='almacen.producto'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='almacen.almacen'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex_filas', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='almacen.producto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='almacen.producto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_proveidos', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='existencia',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='existencias', to='almacen.lote'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='almacen.lote'),
        ),
        migrations.AddField(
            model_name='marcaproducto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_producto', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='almacen.marcaproducto'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='almacen.almacen'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='almacen_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='almacen.almacen'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kardex',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex_filas', to='almacen.movimiento'),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_detalle', to='almacen.lote'),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='almacen.movimiento'),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_detalle', to='almacen.producto'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='movimiento_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex_filas', to='almacen.movimientodetalle'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_almacen', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='rack',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks_almacen', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='almacen.rack'),
        ),
        migrations.AddField(
            model_name='serie',
            name='almacen_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_actuales', to='almacen.almacen'),
        ),
        migrations.AddField(
            model_name='serie',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_almacen', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='serie',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='almacen.lote'),
        ),
        migrations.AddField(
            model_name='serie',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='almacen.producto'),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_detalle', to='almacen.serie'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='almacen_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrantes', to='almacen.almacen'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='almacen_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salientes', to='almacen.almacen'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='movimiento_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencia_entrada', to='almacen.movimiento'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='movimiento_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencia_salida', to='almacen.movimiento'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='recibida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferenciadetalle',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_detalle', to='almacen.lote'),
        ),
        migrations.AddField(
            model_name='transferenciadetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_detalle', to='almacen.producto'),
        ),
        migrations.AddField(
            model_name='transferenciadetalle',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_detalle', to='almacen.serie'),
        ),
        migrations.AddField(
            model_name='transferenciadetalle',
            name='transferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='almacen.transferencia'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='almacen.almacen'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_almacen', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='almacen.nivel'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='almacen.rack'),
        ),
        migrations.AddField(
            model_name='transferenciadetalle',
            name='ubicacion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_destino', to='almacen.ubicacion'),
        ),
        migrations.AddField(
            model_name='transferenciadetalle',
            name='ubicacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_origen', to='almacen.ubicacion'),
        ),
        migrations.AddField(
            model_name='serie',
            name='ubicacion_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_actuales', to='almacen.ubicacion'),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='ubicacion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_destino', to='almacen.ubicacion'),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='ubicacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_origen', to='almacen.ubicacion'),
        ),
        migrations.AddField(
            model_name='existencia',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='existencias', to='almacen.ubicacion'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_medida', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='unidad_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivadas', to='almacen.unidadmedida'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='almacen.unidadmedida'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'activo'], name='almacen_pro_empresa_df98d1_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'tipo'], name='almacen_pro_empresa_c46a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_barras'], name='almacen_pro_codigo__7c37c8_idx'),
        ),
        migrations.AddField(
            model_name='zona',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='almacen.almacen'),
        ),
        migrations.AddField(
            model_name='zona',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_almacen', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='almacen.zona'),
        ),
        migrations.AddField(
            model_name='rack',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='almacen.zona'),
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='MovimientoInventario',
        ),
        migrations.AddIndex(
            model_name='categoriaproducto',
            index=models.Index(fields=['empresa', 'activo'], name='almacen_cat_empresa_f5e662_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriaproducto',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['empresa', 'producto', 'fecha_caducidad'], name='almacen_lot_empresa_43ab20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('empresa', 'producto', 'numero_lote')},
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['empresa', 'tipo', 'atendida'], name='almacen_ale_empresa_9b8170_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['producto', 'almacen'], name='almacen_ale_product_8fc52c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marcaproducto',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['empresa', 'tipo', 'estado'], name='almacen_mov_empresa_ff6840_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['empresa', 'fecha'], name='almacen_mov_empresa_370016_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='movimiento',
            unique_together={('empresa', 'folio')},
        ),
        migrations.AddIndex(
            model_name='kardex',
            index=models.Index(fields=['producto', 'almacen', 'fecha'], name='almacen_kar_product_8b7994_idx'),
        ),
        migrations.AddIndex(
            model_name='kardex',
            index=models.Index(fields=['empresa', 'fecha'], name='almacen_kar_empresa_dd48d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nivel',
            unique_together={('rack', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['empresa', 'estado'], name='almacen_tra_empresa_375a1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transferencia',
            unique_together={('empresa', 'folio')},
        ),
        migrations.AddIndex(
            model_name='serie',
            index=models.Index(fields=['empresa', 'producto', 'estado'], name='almacen_ser_empresa_b20594_idx'),
        ),
        migrations.AddIndex(
            model_name='existencia',
            index=models.Index(fields=['empresa', 'producto'], name='almacen_exi_empresa_997d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='existencia',
            index=models.Index(fields=['empresa', 'almacen'], name='almacen_exi_empresa_4b0095_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='existencia',
            unique_together={('producto', 'almacen', 'ubicacion', 'lote')},
        ),
        migrations.AlterUniqueTogether(
            name='unidadmedida',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='zona',
            unique_together={('almacen', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['almacen', 'activa'], name='almacen_ubi_almacen_e2b10e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together={('almacen', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('zona', 'codigo')},
        ),
    ]
