# Generated by Django 5.2.7 on 2026-05-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_alerta_categoriaproducto_existencia_kardex_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_codigo_barras',
            field=models.CharField(choices=[('QR', 'QR Code'), ('CODE128', 'Code 128 (alfanumerico)'), ('CODE39', 'Code 39 (alfanumerico)'), ('EAN13', 'EAN-13 (13 digitos)'), ('EAN8', 'EAN-8 (8 digitos)'), ('UPCA', 'UPC-A (12 digitos)'), ('ITF', 'Interleaved 2 of 5'), ('NONE', 'Sin codigo')], default='QR', help_text='Simbologia para generar la etiqueta. QR acepta cualquier texto; EAN/UPC exigen longitudes especificas de digitos.', max_length=10),
        ),
    ]
