# Generated by Django 5.2.7 on 2026-05-30 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('cxp', '0002_alter_proveedor_options_proveedor_autorizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='p.ej. ISO 9001:2015', max_length=40)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa'), ('PROVEEDOR', 'A proveedor')], default='INTERNA', max_length=12)),
                ('alcance', models.TextField(blank=True)),
                ('auditor_lider', models.CharField(blank=True, max_length=120)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_realizada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En curso'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='core.empresa')),
                ('norma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgc.norma')),
            ],
            options={
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('instructor', models.CharField(blank=True, max_length=120)),
                ('participantes', models.TextField(blank=True, help_text='Empleados / puestos')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('vigencia_meses', models.PositiveSmallIntegerField(default=12)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('IMPARTIDA', 'Impartida'), ('VENCIDA', 'Vencida')], default='PROGRAMADA', max_length=12)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='core.empresa')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('requiere_calibracion', models.BooleanField(default=True)),
                ('fecha_ultima_calibracion', models.DateField(blank=True, null=True)),
                ('frecuencia_meses', models.PositiveSmallIntegerField(default=12)),
                ('fecha_proxima_calibracion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_sgc', to='core.empresa')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='p.ej. 2026-Q1', max_length=20)),
                ('calidad', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('tiempo_entrega', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('servicio', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('documentacion', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('comentarios', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_proveedor', to='core.empresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_sgc', to='cxp.proveedor')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('proceso', models.CharField(blank=True, max_length=150)),
                ('unidad', models.CharField(blank=True, help_text='%, días, piezas…', max_length=30)),
                ('meta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_actual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sentido', models.CharField(choices=[('MAYOR', 'Mayor es mejor'), ('MENOR', 'Menor es mejor')], default='MAYOR', max_length=6)),
                ('frecuencia', models.CharField(blank=True, help_text='Mensual, trimestral…', max_length=30)),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='core.empresa')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=30)),
                ('tipo', models.CharField(choices=[('CORRECTIVA', 'Acción correctiva'), ('PREVENTIVA', 'Acción preventiva'), ('MEJORA', 'Mejora')], default='CORRECTIVA', max_length=12)),
                ('origen', models.CharField(choices=[('AUDITORIA', 'Auditoría interna'), ('QUEJA', 'Queja de cliente'), ('PROCESO', 'Desviación de proceso'), ('PROVEEDOR', 'Proveedor'), ('OTRO', 'Otro')], default='OTRO', max_length=12)),
                ('descripcion', models.TextField(help_text='Descripción de la no conformidad')),
                ('causa_raiz', models.TextField(blank=True, help_text='Análisis de causa raíz (5 porqués, Ishikawa…)')),
                ('accion', models.TextField(blank=True, help_text='Acción correctiva/preventiva propuesta')),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('fecha_deteccion', models.DateField(auto_now_add=True)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada'), ('VENCIDA', 'Vencida')], default='ABIERTA', max_length=12)),
                ('eficacia_verificada', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_conformidades', to='core.empresa')),
            ],
            options={
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=30)),
                ('tipo', models.CharField(choices=[('QUEJA', 'Queja'), ('RECLAMO', 'Reclamo'), ('SUGERENCIA', 'Sugerencia'), ('FELICITACION', 'Felicitación')], default='QUEJA', max_length=12)),
                ('cliente', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('respuesta', models.TextField(blank=True)),
                ('satisfaccion', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En proceso'), ('RESUELTA', 'Resuelta')], default='ABIERTA', max_length=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='core.empresa')),
                ('no_conformidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgc.noconformidad')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RequisitoISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clausula', models.CharField(help_text='p.ej. 7.1.5', max_length=20)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='sgc.norma')),
            ],
            options={
                'ordering': ['norma', 'orden', 'clausula'],
            },
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NC_MAYOR', 'No conformidad mayor'), ('NC_MENOR', 'No conformidad menor'), ('OBSERVACION', 'Observación'), ('OPORTUNIDAD', 'Oportunidad de mejora'), ('CONFORME', 'Conforme')], default='OBSERVACION', max_length=12)),
                ('descripcion', models.TextField()),
                ('evidencia', models.TextField(blank=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='sgc.auditoria')),
                ('no_conformidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos', to='sgc.noconformidad')),
                ('requisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgc.requisitoiso')),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField()),
                ('es_oportunidad', models.BooleanField(default=False, help_text='True = oportunidad; False = riesgo')),
                ('probabilidad', models.PositiveSmallIntegerField(default=1, help_text='1 a 5')),
                ('impacto', models.PositiveSmallIntegerField(default=1, help_text='1 a 5')),
                ('controles', models.TextField(blank=True)),
                ('plan_mitigacion', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('IDENTIFICADO', 'Identificado'), ('EN_TRATAMIENTO', 'En tratamiento'), ('CONTROLADO', 'Controlado'), ('ACEPTADO', 'Aceptado')], default='IDENTIFICADO', max_length=15)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='core.empresa')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumple', models.CharField(choices=[('NO', 'No cumple'), ('PARCIAL', 'Parcial'), ('SI', 'Cumple'), ('NA', 'No aplica')], default='NO', max_length=10)),
                ('evidencia', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_iso', to='core.empresa')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='sgc.requisitoiso')),
            ],
            options={
                'unique_together': {('empresa', 'requisito')},
            },
        ),
    ]
