# Generated by Django 5.2.7 on 2026-05-30 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sgc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoContexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('F', 'Fortaleza'), ('D', 'Debilidad'), ('O', 'Oportunidad'), ('A', 'Amenaza')], max_length=1)),
                ('descripcion', models.CharField(max_length=400)),
                ('estrategia', models.TextField(blank=True, help_text='Cómo se aprovecha/aborda')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexto', to='core.empresa')),
            ],
            options={
                'ordering': ['tipo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=300)),
                ('meta', models.CharField(blank=True, help_text='p.ej. ≥ 95%', max_length=120)),
                ('indicador', models.CharField(blank=True, help_text='Cómo se mide', max_length=200)),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('avance', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('LOGRADO', 'Logrado'), ('NO_LOGRADO', 'No logrado')], default='EN_CURSO', max_length=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_calidad', to='core.empresa')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ParteInteresada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor'), ('EMPLEADO', 'Empleado/personal'), ('ACCIONISTA', 'Accionista/dueño'), ('AUTORIDAD', 'Autoridad/regulador'), ('COMUNIDAD', 'Comunidad'), ('OTRO', 'Otro')], default='CLIENTE', max_length=12)),
                ('necesidades', models.TextField(blank=True, help_text='Necesidades y expectativas')),
                ('influencia', models.PositiveSmallIntegerField(default=3, help_text='1-5')),
                ('seguimiento', models.CharField(blank=True, help_text='Cómo se les da seguimiento', max_length=300)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes_interesadas', to='core.empresa')),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=150)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('escolaridad', models.CharField(blank=True, max_length=200)),
                ('formacion', models.TextField(blank=True, help_text='Cursos/certificaciones requeridas')),
                ('experiencia', models.CharField(blank=True, max_length=200)),
                ('habilidades', models.TextField(blank=True, help_text='Competencias/habilidades requeridas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_puesto', to='core.empresa')),
            ],
            options={
                'ordering': ['puesto'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=150)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nivel', models.PositiveSmallIntegerField(default=0, help_text='% de cumplimiento del perfil (0-100)')),
                ('brechas', models.TextField(blank=True)),
                ('plan_desarrollo', models.TextField(blank=True, help_text='Capacitación/acciones para cerrar brechas')),
                ('estado', models.CharField(choices=[('CUMPLE', 'Cumple perfil'), ('BRECHA', 'Con brecha'), ('EN_DESARROLLO', 'En desarrollo')], default='BRECHA', max_length=14)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_competencia', to='core.empresa')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='sgc.perfilpuesto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PoliticaCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('aprobada_por', models.CharField(blank=True, max_length=150)),
                ('vigente', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='politica_calidad', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, help_text='p.ej. 2026-S1', max_length=40)),
                ('participantes', models.TextField(blank=True)),
                ('entradas', models.TextField(blank=True, help_text='Estado de acciones previas, cambios, desempeño (KPIs, NC, auditorías, satisfacción, proveedores), recursos, riesgos…')),
                ('conclusiones', models.TextField(blank=True, help_text='Oportunidades de mejora, cambios al SGC, necesidades de recursos')),
                ('acuerdos', models.TextField(blank=True, help_text='Acuerdos, responsables y fechas')),
                ('proxima_fecha', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_direccion', to='core.empresa')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
