# Generated by Django 5.2.7 on 2026-05-31 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('sgc', '0002_elementocontexto_objetivocalidad_parteinteresada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='auditor_lider_user',
            field=models.ForeignKey(blank=True, help_text='Auditor líder (usuario)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_lideradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='responsable_user',
            field=models.ForeignKey(blank=True, help_text='Responsable de la capacitación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacitaciones_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='responsable_user',
            field=models.ForeignKey(blank=True, help_text='Responsable de la calibración', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='responsable_user',
            field=models.ForeignKey(blank=True, help_text='Usuario responsable del cierre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objetivocalidad',
            name='responsable_user',
            field=models.ForeignKey(blank=True, help_text='Responsable del objetivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='responsable_user',
            field=models.ForeignKey(blank=True, help_text='Responsable del tratamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riesgos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActividadSGC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('verbo', models.CharField(choices=[('CREO', 'creó'), ('ACTUALIZO', 'actualizó'), ('CAMBIO_ESTADO', 'cambió el estado'), ('ASIGNO', 'asignó'), ('COMENTO', 'comentó'), ('CERRO', 'cerró'), ('REABRIO', 'reabrió'), ('ADJUNTO', 'adjuntó evidencia'), ('APROBO', 'aprobó'), ('RECHAZO', 'rechazó'), ('VERIFICO', 'verificó eficacia')], default='ACTUALIZO', max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('datos', models.JSONField(blank=True, default=dict, help_text='{campo: [antes, despues]}')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad_sgc', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_sgc', to='core.empresa')),
            ],
            options={
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='sgc_activid_content_93ceac_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComentarioSGC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('texto', models.TextField()),
                ('editado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_sgc', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_sgc', to='core.empresa')),
                ('menciones', models.ManyToManyField(blank=True, related_name='menciones_sgc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='sgc_comenta_content_5556f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificacionCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ASIGNACION', 'Te asignaron'), ('MENCION', 'Te mencionaron'), ('COMENTARIO', 'Nuevo comentario'), ('VENCIMIENTO', 'Vencimiento'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('APROBACION', 'Requiere aprobación'), ('INFO', 'Información')], default='INFO', max_length=14)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, help_text='Ruta del frontend al registro', max_length=300)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_sgc', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_sgc', to='core.empresa')),
            ],
            options={
                'ordering': ['-creada'],
                'indexes': [models.Index(fields=['destinatario', 'leida'], name='sgc_notific_destina_be6136_idx')],
            },
        ),
    ]
