# Generated by Django 5.2.7 on 2026-05-31 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('sgc', '0003_auditoria_auditor_lider_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noconformidad',
            name='aprobada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='verificada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_verificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccionCAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('INMEDIATA', 'Contención/inmediata'), ('CORRECTIVA', 'Correctiva'), ('PREVENTIVA', 'Preventiva')], default='CORRECTIVA', max_length=12)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('fecha_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('HECHA', 'Realizada'), ('VERIFICADA', 'Verificada')], default='PENDIENTE', max_length=12)),
                ('eficacia', models.CharField(choices=[('PENDIENTE', 'Por evaluar'), ('EFICAZ', 'Eficaz'), ('NO_EFICAZ', 'No eficaz')], default='PENDIENTE', max_length=10)),
                ('evidencia', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('no_conformidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='sgc.noconformidad')),
                ('responsable_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_capa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=40)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ESTRATEGICO', 'Estratégico'), ('CLAVE', 'Clave / Operativo'), ('APOYO', 'Apoyo')], default='CLAVE', max_length=12)),
                ('objetivo', models.TextField(blank=True)),
                ('proveedores', models.TextField(blank=True, help_text='Suppliers')),
                ('entradas', models.TextField(blank=True, help_text='Inputs')),
                ('actividades', models.TextField(blank=True, help_text='Process (actividades clave)')),
                ('salidas', models.TextField(blank=True, help_text='Outputs')),
                ('clientes', models.TextField(blank=True, help_text='Customers')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('dueno_user', models.ForeignKey(blank=True, help_text='Dueño del proceso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_dueno', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='core.empresa')),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='indicadorkpi',
            name='proceso_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='sgc.proceso'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='proceso_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riesgos', to='sgc.proceso'),
        ),
        migrations.CreateModel(
            name='TareaImplementacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('columna', models.CharField(choices=[('POR_HACER', 'Por hacer'), ('EN_PROCESO', 'En proceso'), ('IMPLEMENTADO', 'Implementado'), ('VERIFICADO', 'Verificado')], default='POR_HACER', max_length=14)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=6)),
                ('avance', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_implementacion', to='core.empresa')),
                ('requisito', models.ForeignKey(blank=True, help_text='Cláusula ISO que esta tarjeta ayuda a cumplir', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_impl', to='sgc.requisitoiso')),
                ('responsable_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_impl_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['columna', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaSGC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('archivo', models.FileField(upload_to='sgc/evidencias/')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_sgc', to='core.empresa')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_sgc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='sgc_evidenc_content_f824b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicionKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='sgc.indicadorkpi')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('kpi', 'fecha')},
            },
        ),
    ]
