# Generated by Django 5.2.7 on 2026-05-31 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0004_noconformidad_aprobada_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivocalidad',
            name='kpi_ref',
            field=models.ForeignKey(blank=True, help_text='KPI con el que se mide el objetivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos', to='sgc.indicadorkpi'),
        ),
        migrations.AddField(
            model_name='objetivocalidad',
            name='proceso_ref',
            field=models.ForeignKey(blank=True, help_text='Proceso del que deriva el objetivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos', to='sgc.proceso'),
        ),
    ]
