# Generated by Django 5.2.7 on 2026-05-31 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0005_objetivocalidad_kpi_ref_objetivocalidad_proceso_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('peso', models.PositiveSmallIntegerField(default=1, help_text='Peso relativo en el avance')),
                ('avance', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='sgc.objetivocalidad')),
                ('responsable_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_objetivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
