# Generated by Django 5.2.7 on 2026-05-31 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sgc', '0008_revisiondireccion_creado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=24, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('preguntas', models.JSONField(blank=True, default=list)),
                ('color', models.CharField(default='#EC4899', max_length=20)),
                ('mensaje_gracias', models.CharField(blank=True, default='¡Gracias por tu respuesta!', max_length=300)),
                ('crear_queja', models.BooleanField(default=True, help_text='Crea un caso en Quejas con cada respuesta')),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='core.empresa')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(blank=True, default=dict)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('cliente_email', models.CharField(blank=True, max_length=200)),
                ('satisfaccion', models.PositiveSmallIntegerField(blank=True, help_text='1-5 derivado', null=True)),
                ('nps', models.PositiveSmallIntegerField(blank=True, help_text='0-10 derivado', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='sgc.encuesta')),
                ('queja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgc.queja')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
