# Generated by Django 5.2.7 on 2026-05-31 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0009_encuesta_respuestaencuesta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacioncompetencia',
            name='capacitacion_ref',
            field=models.ForeignKey(blank=True, help_text='Capacitación que cierra las brechas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_competencia', to='sgc.capacitacion'),
        ),
        migrations.AddField(
            model_name='evaluacioncompetencia',
            name='eficacia',
            field=models.CharField(choices=[('PENDIENTE', 'Por evaluar'), ('EFICAZ', 'Eficaz'), ('NO_EFICAZ', 'No eficaz')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='evaluacioncompetencia',
            name='fecha_reevaluacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacioncompetencia',
            name='persona_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_competencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilpuesto',
            name='funciones',
            field=models.TextField(blank=True, help_text='Funciones/responsabilidades del puesto'),
        ),
        migrations.CreateModel(
            name='CompetenciaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONOCIMIENTO', 'Conocimiento'), ('TECNICA', 'Habilidad técnica'), ('BLANDA', 'Habilidad blanda'), ('CERTIFICACION', 'Certificación'), ('EXPERIENCIA', 'Experiencia')], default='CONOCIMIENTO', max_length=14)),
                ('nombre', models.CharField(max_length=200)),
                ('nivel_requerido', models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado'), (4, 'Experto')], default=2)),
                ('obligatoria', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='sgc.perfilpuesto')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('CONOCIMIENTO', 'Conocimiento'), ('TECNICA', 'Habilidad técnica'), ('BLANDA', 'Habilidad blanda'), ('CERTIFICACION', 'Certificación'), ('EXPERIENCIA', 'Experiencia')], default='CONOCIMIENTO', max_length=14)),
                ('nivel_requerido', models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado'), (4, 'Experto')], default=2)),
                ('nivel_actual', models.PositiveSmallIntegerField(default=0, help_text='0 = no lo tiene')),
                ('obligatoria', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgc.competenciaperfil')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sgc.evaluacioncompetencia')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
