# Generated by Django 5.2.7 on 2026-06-02 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sgc', '0010_evaluacioncompetencia_capacitacion_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='elementocontexto',
            name='responsable_user',
            field=models.ForeignKey(blank=True, help_text='Responsable de la estrategia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contexto_asignado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacionproveedor',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EVALUADO', 'Evaluado'), ('SEGUIMIENTO', 'En seguimiento'), ('CERRADO', 'Cerrado')], default='EVALUADO', max_length=12),
        ),
        migrations.AddField(
            model_name='evaluacionproveedor',
            name='plan_mejora',
            field=models.TextField(blank=True, help_text='Plan de mejora acordado con el proveedor'),
        ),
        migrations.AddField(
            model_name='evaluacionproveedor',
            name='responsable_user',
            field=models.ForeignKey(blank=True, help_text='Evaluador responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_proveedor_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicadorkpi',
            name='responsable_user',
            field=models.ForeignKey(blank=True, help_text='Responsable de mantener el indicador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='queja',
            name='fecha_compromiso',
            field=models.DateField(blank=True, help_text='Fecha objetivo de respuesta', null=True),
        ),
        migrations.AddField(
            model_name='queja',
            name='responsable_user',
            field=models.ForeignKey(blank=True, help_text='Responsable de atender la queja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quejas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SalidaNoConforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.TextField(help_text='Qué producto/servicio y por qué no cumple')),
                ('origen', models.CharField(choices=[('RECEPCION', 'Recepción / entrada'), ('PROCESO', 'Durante el proceso'), ('FINAL', 'Inspección final'), ('CLIENTE', 'Detectado por el cliente'), ('AUDITORIA', 'Auditoría')], default='PROCESO', max_length=12)),
                ('cantidad', models.CharField(blank=True, help_text='p.ej. 12 piezas, 3 servicios', max_length=60)),
                ('requisito_incumplido', models.CharField(blank=True, max_length=300)),
                ('disposicion', models.CharField(choices=[('CORRECCION', 'Corrección / reproceso'), ('SEGREGACION', 'Segregación / contención'), ('DEVOLUCION', 'Devolución al proveedor'), ('CONCESION', 'Aceptación bajo concesión'), ('DESECHO', 'Desecho / scrap'), ('RECLASIFICACION', 'Reclasificación')], default='CORRECCION', max_length=15)),
                ('autorizo_concesion', models.CharField(blank=True, help_text='Quién autorizó (si la disposición es concesión)', max_length=200)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_TRATAMIENTO', 'En tratamiento'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=15)),
                ('fecha_deteccion', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_nc_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas_no_conformes', to='core.empresa')),
                ('no_conformidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_origen', to='sgc.noconformidad')),
                ('proceso_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_no_conformes', to='sgc.proceso')),
                ('responsable_user', models.ForeignKey(blank=True, help_text='Responsable del tratamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_nc_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
