# Generated by Django 5.2.7 on 2026-06-02 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sgc', '0011_elementocontexto_responsable_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicacionSGC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(help_text='Qué se comunica', max_length=250)),
                ('direccion', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa'), ('AMBAS', 'Ambas')], default='INTERNA', max_length=10)),
                ('cuando', models.CharField(blank=True, help_text='Frecuencia / cuándo', max_length=150)),
                ('a_quien', models.CharField(blank=True, help_text='Audiencia / partes interesadas', max_length=250)),
                ('como', models.CharField(blank=True, help_text='Canal/medio', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_sgc', to='core.empresa')),
                ('responsable_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicaciones_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['que'],
            },
        ),
        migrations.CreateModel(
            name='ConocimientoOrganizacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('LECCION', 'Lección aprendida'), ('MEJOR_PRACTICA', 'Mejor práctica'), ('EXPERIENCIA', 'Experiencia'), ('FUENTE_EXTERNA', 'Fuente externa'), ('OTRO', 'Otro')], default='LECCION', max_length=15)),
                ('area', models.CharField(blank=True, help_text='Proceso/área relacionada', max_length=150)),
                ('contenido', models.TextField(help_text='Descripción del conocimiento / lección')),
                ('origen', models.CharField(blank=True, help_text='De dónde proviene (NC, proyecto, etc.)', max_length=200)),
                ('etiquetas', models.CharField(blank=True, max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('autor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conocimiento_aportado', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conocimiento_sgc', to='core.empresa')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='GestionCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='En qué consiste el cambio')),
                ('justificacion', models.TextField(blank=True, help_text='Propósito y motivo del cambio')),
                ('consecuencias', models.TextField(blank=True, help_text='Consecuencias potenciales')),
                ('recursos', models.TextField(blank=True, help_text='Recursos necesarios')),
                ('impacto_integridad', models.CharField(blank=True, help_text='Cómo se preserva la integridad del SGC', max_length=300)),
                ('autorizado_por', models.CharField(blank=True, max_length=150)),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PROPUESTO', 'Propuesto'), ('APROBADO', 'Aprobado'), ('EN_PROCESO', 'En proceso'), ('IMPLEMENTADO', 'Implementado'), ('RECHAZADO', 'Rechazado')], default='PROPUESTO', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_sgc', to='core.empresa')),
                ('responsable_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='HitoCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('DIAGNOSTICO', '1. Diagnóstico inicial'), ('PLANEACION', '2. Planeación y liderazgo'), ('DOCUMENTACION', '3. Documentación del SGC'), ('IMPLEMENTACION', '4. Implementación'), ('MEDICION', '5. Medición y seguimiento'), ('AUDITORIA_INTERNA', '6. Auditoría interna'), ('REVISION_DIRECCION', '7. Revisión por la dirección'), ('PREAUDITORIA', '8. Pre-auditoría / acciones'), ('CERTIFICACION', '9. Auditoría de certificación')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=400)),
                ('clausula', models.CharField(blank=True, max_length=20)),
                ('ruta', models.CharField(blank=True, max_length=120)),
                ('orden', models.PositiveSmallIntegerField(default=100)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos_certificacion', to='core.empresa')),
                ('responsable_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hitos_certificacion_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Null = checklist global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists_auditoria', to='core.empresa')),
                ('norma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgc.norma')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clausula', models.CharField(blank=True, max_length=20)),
                ('pregunta', models.TextField()),
                ('guia', models.CharField(blank=True, help_text='Qué evidencia buscar', max_length=400)),
                ('orden', models.PositiveSmallIntegerField(default=100)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sgc.plantillachecklist')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=40)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('POLITICA', 'Política'), ('MANUAL', 'Manual'), ('PROCEDIMIENTO', 'Procedimiento'), ('INSTRUCTIVO', 'Instructivo'), ('FORMATO', 'Formato'), ('PLAN', 'Plan'), ('MATRIZ', 'Matriz'), ('OTRO', 'Otro')], default='PROCEDIMIENTO', max_length=15)),
                ('clausula', models.CharField(blank=True, help_text='Cláusula ISO que cubre', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('contenido', models.TextField(help_text='Cuerpo del documento, admite {{empresa}}, {{fecha}}, etc.')),
                ('obligatoria', models.BooleanField(default=False, help_text='Documento exigido por la norma')),
                ('orden', models.PositiveSmallIntegerField(default=100)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Null = plantilla global del sistema', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_sgc', to='core.empresa')),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=40)),
                ('nombre', models.CharField(max_length=200)),
                ('proceso', models.CharField(blank=True, max_length=150)),
                ('soporte', models.CharField(choices=[('DIGITAL', 'Digital'), ('FISICO', 'Físico'), ('AMBOS', 'Ambos')], default='DIGITAL', max_length=10)),
                ('ubicacion', models.CharField(blank=True, help_text='Dónde se almacena', max_length=200)),
                ('retencion_meses', models.PositiveSmallIntegerField(default=36, help_text='Tiempo de retención (meses)')),
                ('disposicion', models.CharField(choices=[('ELIMINAR', 'Eliminar'), ('ARCHIVAR', 'Archivar'), ('CONSERVAR', 'Conservar indefinidamente')], default='ARCHIVAR', max_length=12)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_calidad', to='core.empresa')),
                ('proceso_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='sgc.proceso')),
                ('responsable_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['codigo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('objetivo', models.TextField(blank=True)),
                ('alcance', models.TextField(blank=True)),
                ('criterios', models.CharField(blank=True, help_text='Normas/criterios de referencia', max_length=300)),
                ('aprobado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_auditoria', to='core.empresa')),
                ('responsable_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_auditoria_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-anio'],
                'unique_together': {('empresa', 'anio')},
            },
        ),
    ]
