# Generated by Django 5.2.7 on 2026-06-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_empleado_apellido'),
        ('sgc', '0012_comunicacionsgc_conocimientoorganizacional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='empleados',
            field=models.ManyToManyField(blank=True, help_text='Empleados de RH inscritos en esta capacitación', related_name='capacitaciones_sgc', to='rh.empleado'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='participantes',
            field=models.TextField(blank=True, help_text='Empleados / puestos (texto libre)'),
        ),
    ]
