# Generated by Django 5.2.7 on 2026-06-03 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_empleado_apellido'),
        ('sgc', '0013_capacitacion_empleados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='calificacion_minima',
            field=models.DecimalField(decimal_places=2, default=70, help_text='Mínima para aprobar', max_digits=5),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='requiere_calificacion',
            field=models.BooleanField(default=True, help_text='Si no aplica, solo se registra asistencia/nombre y evidencia'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calificación general (opcional; las individuales van por participante)', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='ParticipanteCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre del participante (si no es empleado de RH)', max_length=200)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('ASISTIO', 'Asistió'), ('APROBADO', 'Aprobado'), ('NO_APROBADO', 'No aprobado'), ('AUSENTE', 'Ausente')], default='INSCRITO', max_length=12)),
                ('evidencia', models.FileField(blank=True, help_text='Constancia / evidencia individual', null=True, upload_to='sgc/capacitaciones/')),
                ('evidencia_nombre', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes_lista', to='sgc.capacitacion')),
                ('empleado', models.ForeignKey(blank=True, help_text='Empleado de RH (opcional si es externo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participaciones_capacitacion', to='rh.empleado')),
            ],
            options={
                'ordering': ['nombre', 'id'],
            },
        ),
    ]
