# Generated by Django 5.2.7 on 2026-06-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0014_capacitacion_calificacion_minima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantecapacitacion',
            name='intentos',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número de veces que ha presentado el curso'),
        ),
    ]
