# Generated by Django 5.2.7 on 2026-06-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0015_participantecapacitacion_intentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantecapacitacion',
            name='reprogramado',
            field=models.BooleanField(default=False, help_text='True si este reprobado ya fue movido a otra edición del curso'),
        ),
    ]
