# Generated by Django 5.2.7 on 2026-06-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0016_participantecapacitacion_reprogramado'),
    ]

    operations = [
        migrations.AddField(
            model_name='noconformidad',
            name='categoria_causa',
            field=models.CharField(blank=True, choices=[('METODO', 'Método'), ('MAQUINA', 'Maquinaria/Equipo'), ('MANO_OBRA', 'Mano de obra'), ('MATERIAL', 'Material'), ('MEDICION', 'Medición'), ('MEDIO', 'Medio ambiente')], help_text='Categoría 6M de la causa raíz principal (para análisis de Pareto)', max_length=20),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='cinco_porques',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='ishikawa',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='noconformidad',
            name='causa_raiz',
            field=models.TextField(blank=True, help_text='Análisis de causa raíz (resumen)'),
        ),
    ]
