# Generated by Django 5.2.7 on 2026-06-03 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sgc', '0017_noconformidad_categoria_causa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaChecklistAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clausula', models.CharField(blank=True, max_length=20)),
                ('pregunta', models.TextField(blank=True)),
                ('resultado', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No conforme'), ('OBSERVACION', 'Observación'), ('NA', 'No aplica'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=12)),
                ('nota', models.TextField(blank=True, help_text='Evidencia/observación del auditor')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_checklist', to='sgc.auditoria')),
                ('requisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgc.requisitoiso')),
            ],
            options={
                'ordering': ['clausula', 'id'],
                'unique_together': {('auditoria', 'requisito')},
            },
        ),
        migrations.CreateModel(
            name='SnapshotMadurez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('madurez', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('cumplimiento_iso', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('nc_abiertas', models.PositiveIntegerField(default=0)),
                ('nc_cerradas', models.PositiveIntegerField(default=0)),
                ('riesgos_altos', models.PositiveIntegerField(default=0)),
                ('kpis_en_meta', models.PositiveIntegerField(default=0)),
                ('kpis_total', models.PositiveIntegerField(default=0)),
                ('objetivos_logrados', models.PositiveIntegerField(default=0)),
                ('satisfaccion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_madurez', to='core.empresa')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('empresa', 'fecha')},
            },
        ),
    ]
