# Generated by Django 5.2.8 on 2026-06-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0018_respuestachecklistauditoria_snapshotmadurez'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestioncambio',
            name='fecha_implementacion',
            field=models.DateField(blank=True, help_text='Fecha real de implementación', null=True),
        ),
        migrations.AddField(
            model_name='gestioncambio',
            name='plan_accion',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gestioncambio',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=8),
        ),
        migrations.AddField(
            model_name='gestioncambio',
            name='riesgo_impacto',
            field=models.PositiveSmallIntegerField(default=0, help_text='Impacto 1-5 (0 = sin evaluar)'),
        ),
        migrations.AddField(
            model_name='gestioncambio',
            name='riesgo_probabilidad',
            field=models.PositiveSmallIntegerField(default=0, help_text='Probabilidad 1-5 (0 = sin evaluar)'),
        ),
        migrations.AddField(
            model_name='gestioncambio',
            name='tipo',
            field=models.CharField(choices=[('PROCESO', 'Proceso'), ('DOCUMENTO', 'Documento'), ('INFRAESTRUCTURA', 'Infraestructura'), ('PROVEEDOR', 'Proveedor'), ('ORGANIZACIONAL', 'Organizacional'), ('TECNOLOGICO', 'Tecnológico'), ('PRODUCTO', 'Producto/Servicio'), ('OTRO', 'Otro')], default='PROCESO', help_text='Categoría del cambio (para análisis y trazabilidad)', max_length=16),
        ),
    ]
