# Generated by Django 5.2.7 on 2026-05-27 22:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("rh", "0004_empleado_banco_clave_empleado_clabe_interbancaria_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CFDINomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serie", models.CharField(default="N", max_length=10)),
                ("folio", models.CharField(blank=True, max_length=20)),
                ("uuid", models.CharField(blank=True, db_index=True, max_length=40)),
                ("fecha_timbrado", models.DateTimeField(blank=True, null=True)),
                ("sello_sat", models.TextField(blank=True)),
                ("sello_cfdi", models.TextField(blank=True)),
                ("cadena_original", models.TextField(blank=True)),
                ("no_certificado_sat", models.CharField(blank=True, max_length=40)),
                (
                    "xml",
                    models.TextField(
                        blank=True, help_text="XML completo timbrado por el PAC"
                    ),
                ),
                ("pdf_url", models.URLField(blank=True)),
                ("qr_url", models.URLField(blank=True)),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("TIMBRADO", "Timbrado · vigente"),
                            ("CANCELADO", "Cancelado"),
                            ("ERROR", "Error al timbrar"),
                        ],
                        default="BORRADOR",
                        max_length=12,
                    ),
                ),
                (
                    "motivo_cancelacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "01 · Comprobante con errores con relacion"),
                            ("02", "02 · Comprobante con errores sin relacion"),
                            ("03", "03 · No se llevo a cabo la operacion"),
                            (
                                "04",
                                "04 · Operacion nominativa relacionada en factura global",
                            ),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "folio_sustituye",
                    models.CharField(
                        blank=True,
                        help_text="UUID del CFDI que sustituye (motivo 01)",
                        max_length=40,
                    ),
                ),
                ("error_pac", models.TextField(blank=True)),
                ("respuesta_pac", models.JSONField(blank=True, default=dict)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("fecha_cancelacion", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cfdi_nomina_cancelados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cfdi_nomina_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cfdi_nomina",
                        to="core.empresa",
                    ),
                ),
                (
                    "timbrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cfdi_nomina_timbrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CFDI de nomina",
                "verbose_name_plural": "CFDI de nomina",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="BitacoraFiscalNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("TIMBRAR", "Timbrar"),
                            ("CANCELAR", "Cancelar"),
                            ("CONSULTAR", "Consultar"),
                            ("DESCARGAR", "Descargar"),
                        ],
                        max_length=12,
                    ),
                ),
                ("exitoso", models.BooleanField(default=True)),
                ("request_body", models.JSONField(blank=True, default=dict)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bitacora_nomina",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cfdi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bitacora",
                        to="nomina.cfdinomina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitacora fiscal nomina",
                "verbose_name_plural": "Bitacora fiscal nomina",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ConfigNominaEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(
                        choices=[("FACTURA_COM", "Factura.com"), ("OTRO", "Otro PAC")],
                        default="FACTURA_COM",
                        max_length=20,
                    ),
                ),
                (
                    "pac_api_key",
                    models.CharField(
                        blank=True,
                        help_text="F-PLUGIN-API-KEY (o similar) del PAC",
                        max_length=200,
                    ),
                ),
                (
                    "pac_secret_key",
                    models.CharField(
                        blank=True,
                        help_text="F-PLUGIN-SECRET-KEY del PAC",
                        max_length=200,
                    ),
                ),
                (
                    "pac_endpoint",
                    models.URLField(
                        default="https://sandbox.factura.com",
                        help_text="URL base del PAC (sandbox o produccion)",
                    ),
                ),
                ("pac_sandbox", models.BooleanField(default=True)),
                (
                    "registro_patronal",
                    models.CharField(
                        blank=True,
                        help_text="Numero IMSS de registro patronal",
                        max_length=20,
                    ),
                ),
                ("rfc_patron_origen", models.CharField(blank=True, max_length=13)),
                (
                    "riesgo_puesto_default",
                    models.CharField(
                        default="1",
                        help_text="Clave c_RiesgoPuesto por defecto si el puesto no lo define",
                        max_length=2,
                    ),
                ),
                ("serie_default", models.CharField(default="N", max_length=10)),
                (
                    "folio_actual",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Folio interno para CFDI de nomina; se incrementa solo",
                    ),
                ),
                (
                    "csd_cer_file",
                    models.FileField(blank=True, null=True, upload_to="csd/"),
                ),
                (
                    "csd_key_file",
                    models.FileField(blank=True, null=True, upload_to="csd/"),
                ),
                ("csd_password", models.CharField(blank=True, max_length=200)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_nomina",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuracion de nomina (PAC)",
                "verbose_name_plural": "Configuracion de nomina (PAC)",
            },
        ),
        migrations.CreateModel(
            name="NominaEmpleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dias_pagados",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "salario_diario",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "salario_diario_integrado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="SDI: salario diario integrado (incluye prestaciones)",
                        max_digits=12,
                    ),
                ),
                (
                    "salario_base_cot_apor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="SBC: salario base de cotizacion para IMSS",
                        max_digits=12,
                    ),
                ),
                (
                    "total_percepciones",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_deducciones",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_otros_pagos",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_neto",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_gravado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_exento",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibos_nomina",
                        to="rh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo de nomina",
                "verbose_name_plural": "Recibos de nomina",
                "ordering": ["empleado__nombre"],
            },
        ),
        migrations.CreateModel(
            name="IncidenciaNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INCAP", "Incapacidad"),
                            ("FALTA", "Falta"),
                            ("HE_DOBLE", "Hora extra doble"),
                            ("HE_TRIPLE", "Hora extra triple"),
                            ("VAC", "Vacaciones"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "tipo_incapacidad_sat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "Riesgo de trabajo"),
                            ("02", "Enfermedad general"),
                            ("03", "Maternidad"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "dias",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "horas",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("motivo", models.CharField(blank=True, max_length=200)),
                (
                    "nomina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidencias",
                        to="nomina.nominaempleado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConceptoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("P", "Percepcion"),
                            ("D", "Deduccion"),
                            ("O", "Otro pago"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "clave_sat",
                    models.CharField(
                        help_text="c_TipoPercepcion / c_TipoDeduccion / c_TipoOtroPago",
                        max_length=4,
                    ),
                ),
                (
                    "clave_local",
                    models.CharField(
                        blank=True,
                        help_text="Clave interna de la empresa para este concepto",
                        max_length=20,
                    ),
                ),
                ("concepto", models.CharField(max_length=200)),
                (
                    "importe_gravado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "importe_exento",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "nomina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conceptos",
                        to="nomina.nominaempleado",
                    ),
                ),
            ],
            options={
                "ordering": ["tipo", "clave_sat"],
            },
        ),
        migrations.AddField(
            model_name="cfdinomina",
            name="nomina_empleado",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cfdi_obj",
                to="nomina.nominaempleado",
            ),
        ),
        migrations.CreateModel(
            name="PeriodoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: '1ra quincena Mayo 2026'", max_length=120
                    ),
                ),
                (
                    "tipo_nomina",
                    models.CharField(
                        choices=[("O", "Ordinaria"), ("E", "Extraordinaria")],
                        default="O",
                        max_length=1,
                    ),
                ),
                (
                    "periodicidad_pago",
                    models.CharField(
                        default="04",
                        help_text="Clave c_PeriodicidadPago: 02 Semanal, 04 Quincenal, 05 Mensual",
                        max_length=4,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("fecha_pago", models.DateField()),
                ("num_dias_pagados", models.PositiveIntegerField(default=15)),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("ABIERTO", "Abierto · capturando"),
                            ("CALCULADO", "Calculado · listo para timbrar"),
                            ("TIMBRADO", "Timbrado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="ABIERTO",
                        max_length=12,
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=300)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("cerrado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="periodos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodos_nomina",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Periodo de nomina",
                "verbose_name_plural": "Periodos de nomina",
                "ordering": ["-fecha_pago", "-fecha_inicio"],
            },
        ),
        migrations.AddField(
            model_name="nominaempleado",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recibos",
                to="nomina.periodonomina",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="nominaempleado",
            unique_together={("periodo", "empleado")},
        ),
    ]
