# Generated by Django 5.2.7 on 2026-05-26 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carta_porte", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfc", models.CharField(max_length=13)),
                ("razon_social", models.CharField(max_length=255)),
                ("nombre_comercial", models.CharField(blank=True, max_length=255)),
                ("regimen_fiscal", models.CharField(blank=True, max_length=10)),
                ("cp_fiscal", models.CharField(blank=True, max_length=10)),
                (
                    "uso_cfdi_default",
                    models.CharField(blank=True, default="G03", max_length=10),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("direccion", models.CharField(blank=True, max_length=300)),
                ("uid_pac", models.CharField(blank=True, max_length=50)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["razon_social"],
                "unique_together": {("empresa", "rfc")},
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.PositiveIntegerField()),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                ("fecha_timbrado", models.DateTimeField(blank=True, null=True)),
                ("tipo_comprobante", models.CharField(default="I", max_length=2)),
                ("moneda", models.CharField(default="MXN", max_length=3)),
                (
                    "tipo_cambio",
                    models.DecimalField(decimal_places=4, default=1, max_digits=10),
                ),
                ("forma_pago", models.CharField(default="99", max_length=5)),
                ("metodo_pago", models.CharField(default="PUE", max_length=5)),
                ("uso_cfdi", models.CharField(default="G03", max_length=10)),
                ("lugar_expedicion", models.CharField(blank=True, max_length=10)),
                ("condiciones_pago", models.CharField(blank=True, max_length=200)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "iva_trasladado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "iva_retenido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "isr_retenido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("TIMBRADA", "Timbrada"),
                            ("CANCELADA", "Cancelada"),
                            ("ERROR", "Error al timbrar"),
                        ],
                        default="BORRADOR",
                        max_length=15,
                    ),
                ),
                (
                    "folio_fiscal",
                    models.CharField(blank=True, help_text="UUID SAT", max_length=64),
                ),
                ("pac_uid", models.CharField(blank=True, max_length=64)),
                ("pac_serie_id", models.CharField(blank=True, max_length=40)),
                (
                    "xml",
                    models.FileField(blank=True, null=True, upload_to="facturas/xml/"),
                ),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="facturas/pdf/"),
                ),
                ("motivo_cancelacion", models.CharField(blank=True, max_length=10)),
                ("folio_sustitucion", models.CharField(blank=True, max_length=64)),
                ("log_pac", models.JSONField(blank=True, default=dict)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "carta_porte",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factura",
                        to="carta_porte.cartaporte",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="facturacion.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facturas",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_emision"],
            },
        ),
        migrations.CreateModel(
            name="ConceptoFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=400)),
                ("clave_prod_serv", models.CharField(max_length=15)),
                ("clave_unidad", models.CharField(max_length=6)),
                ("unidad", models.CharField(blank=True, max_length=40)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("objeto_imp", models.CharField(default="02", max_length=4)),
                (
                    "tasa_iva",
                    models.DecimalField(decimal_places=4, default=0.16, max_digits=6),
                ),
                (
                    "retencion_iva",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "retencion_isr",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("no_identificacion", models.CharField(blank=True, max_length=100)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conceptos",
                        to="facturacion.factura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.PositiveIntegerField()),
                ("fecha_pago", models.DateTimeField()),
                ("forma_pago", models.CharField(max_length=5)),
                ("moneda", models.CharField(default="MXN", max_length=3)),
                (
                    "tipo_cambio",
                    models.DecimalField(decimal_places=4, default=1, max_digits=10),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                ("numero_operacion", models.CharField(blank=True, max_length=80)),
                ("cuenta_ordenante", models.CharField(blank=True, max_length=50)),
                ("banco_ordenante", models.CharField(blank=True, max_length=50)),
                ("cuenta_beneficiario", models.CharField(blank=True, max_length=50)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("TIMBRADA", "Timbrada"),
                            ("CANCELADA", "Cancelada"),
                            ("ERROR", "Error al timbrar"),
                        ],
                        default="BORRADOR",
                        max_length=15,
                    ),
                ),
                ("folio_fiscal", models.CharField(blank=True, max_length=64)),
                ("pac_uid", models.CharField(blank=True, max_length=64)),
                (
                    "xml",
                    models.FileField(blank=True, null=True, upload_to="pagos/xml/"),
                ),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="pagos/pdf/"),
                ),
                ("log_pac", models.JSONField(blank=True, default=dict)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_pago"],
            },
        ),
        migrations.CreateModel(
            name="DoctoRelacionado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_parcialidad", models.PositiveIntegerField(default=1)),
                (
                    "saldo_anterior",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "importe_pagado",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "saldo_insoluto",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_recibidos",
                        to="facturacion.factura",
                    ),
                ),
                (
                    "pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="facturacion.pago",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letra", models.CharField(max_length=10)),
                ("descripcion", models.CharField(blank=True, max_length=120)),
                (
                    "tipo_comprobante",
                    models.CharField(
                        choices=[
                            ("I", "Ingreso"),
                            ("E", "Egreso"),
                            ("T", "Traslado"),
                            ("N", "Nomina"),
                            ("P", "Pago"),
                        ],
                        default="I",
                        max_length=2,
                    ),
                ),
                ("requiere_carta_porte", models.BooleanField(default=False)),
                (
                    "pac_serie_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de la serie en el PAC (Factura.com)",
                        max_length=40,
                    ),
                ),
                ("folio_actual", models.PositiveIntegerField(default=1)),
                ("activa", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["empresa", "letra"],
                "unique_together": {("empresa", "letra")},
            },
        ),
        migrations.AddField(
            model_name="pago",
            name="serie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos",
                to="facturacion.serie",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="serie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="facturas",
                to="facturacion.serie",
            ),
        ),
        migrations.CreateModel(
            name="ProductoServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_interno", models.CharField(blank=True, max_length=40)),
                ("descripcion", models.CharField(max_length=300)),
                ("clave_prod_serv", models.CharField(max_length=15)),
                ("clave_unidad", models.CharField(max_length=6)),
                ("unidad_descripcion", models.CharField(blank=True, max_length=80)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "objeto_imp",
                    models.CharField(
                        default="02",
                        help_text="01=No objeto, 02=Si objeto, 03=Si objeto y no obligado",
                        max_length=4,
                    ),
                ),
                (
                    "tasa_iva",
                    models.DecimalField(decimal_places=4, default=0.16, max_digits=6),
                ),
                ("aplica_retencion_isr", models.BooleanField(default=False)),
                ("aplica_retencion_iva", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["descripcion"],
                "unique_together": {("empresa", "codigo_interno")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="factura",
            unique_together={("empresa", "serie", "folio")},
        ),
    ]
