# Generated by Django 5.2.7 on 2026-05-30 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='factura_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito', to='facturacion.factura'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_relacion',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
