# Generated by Django 5.2.7 on 2026-05-28 13:34

import apps.chat.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DIRECT', 'Directa 1-a-1'), ('GROUP', 'Grupo')], default='DIRECT', max_length=10)),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('ultimo_mensaje_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ultimo_mensaje_en'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('editado_en', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('es_sistema', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat.conversation')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.chat.models.attachment_upload_to)),
                ('nombre_original', models.CharField(max_length=255)),
                ('mime', models.CharField(blank=True, max_length=120)),
                ('tamano', models.PositiveBigIntegerField(default=0)),
                ('es_imagen', models.BooleanField(default=False)),
                ('ancho', models.PositiveIntegerField(blank=True, null=True)),
                ('alto', models.PositiveIntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='chat.message')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_admin', models.BooleanField(default=False)),
                ('silenciado', models.BooleanField(default=False)),
                ('unido_en', models.DateTimeField(auto_now_add=True)),
                ('salido_en', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_membresias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'salido_en'], name='chat_member_user_id_27cdf0_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'user'), name='chat_membership_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'creado'], name='chat_messag_convers_c5850f_idx'),
        ),
    ]
