# Generated by Django 5.2.8 on 2026-06-06 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta_porte', '0002_operador_licencia_vencimiento'),
        ('core', '0001_initial'),
        ('facturacion', '0003_cliente_calle_cliente_colonia_cliente_estado_and_more'),
        ('flota', '0004_termo_fecha_ultimo_servicio_and_more'),
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viaje',
            options={'ordering': ['-fecha_viaje', '-creado']},
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='autotransporte',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='notas',
        ),
        migrations.AddField(
            model_name='viaje',
            name='carta_porte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaje', to='carta_porte.cartaporte'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='eco_remolque',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_viaje',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='folio_carga',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='viaje',
            name='folio_carta',
            field=models.CharField(blank=True, help_text='Folio de la carta de traslado (autogenerado)', max_length=40),
        ),
        migrations.AddField(
            model_name='viaje',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='placa_remolque',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='viaje',
            name='sueldo_operador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='viaje',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='flota.unidad'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='facturacion.cliente'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_destino', to='carta_porte.ubicacion'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_RUTA', 'En ruta'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PLANIFICADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='numero',
            field=models.CharField(blank=True, help_text='Consecutivo interno', max_length=40),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='carta_porte.operador'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_origen', to='carta_porte.ubicacion'),
        ),
        migrations.CreateModel(
            name='Determinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=200)),
                ('cliente', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='determinantes', to='core.empresa')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='determinantes', to='carta_porte.ubicacion')),
            ],
            options={
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ParadaViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('kms', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('determinante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paradas', to='viajes.determinante')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas_viaje', to='carta_porte.ubicacion')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='viajes.viaje')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MercanciaViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_producto', models.CharField(blank=True, help_text='ClaveProdServ / CP SAT', max_length=15)),
                ('descripcion', models.CharField(max_length=400)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('peso_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unidad_medida', models.CharField(default='H87', max_length=6)),
                ('material_peligroso', models.BooleanField(default=False)),
                ('clave_material_peligroso', models.CharField(blank=True, max_length=10)),
                ('embalaje', models.CharField(blank=True, max_length=10)),
                ('descripcion_embalaje', models.CharField(blank=True, max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercancias', to='viajes.viaje')),
                ('parada_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercancias_destino', to='viajes.paradaviaje')),
                ('parada_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercancias_origen', to='viajes.paradaviaje')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TimbreViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=64)),
                ('estado', models.CharField(choices=[('TIMBRADO', 'Timbrado'), ('CANCELADO', 'Cancelado')], default='TIMBRADO', max_length=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=20)),
                ('log', models.JSONField(blank=True, default=dict)),
                ('carta_porte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timbres_viaje', to='carta_porte.cartaporte')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timbres', to='viajes.viaje')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
