# Generated by Django 5.2.8 on 2026-06-07 01:08

import apps.viajes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracionempresa_pac_serie_cp_id'),
        ('viajes', '0002_alter_viaje_options_remove_viaje_autotransporte_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGastoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_gasto_viaje', to='core.empresa')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='GastoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='viajes.categoriagastoviaje')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_viaje_creados', to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='viajes.viaje')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaGastoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.viajes.models._evidencia_gasto_path)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('mime', models.CharField(blank=True, max_length=120)),
                ('subido', models.DateTimeField(auto_now_add=True)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='viajes.gastoviaje')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
