# Generated by Django 5.2.7 on 2026-05-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['razon_social']},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='autorizado',
            field=models.BooleanField(default=False, help_text='Validado administrativamente'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='clabe',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuenta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_credito',
            field=models.PositiveIntegerField(default=0, help_text='Días otorgados para pagar'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='requiere_xml',
            field=models.BooleanField(default=False, help_text='Exige subir XML obligatoriamente'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='saldo_a_favor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto que el proveedor nos adeuda', max_digits=14),
        ),
    ]
